LANGUAGE.getCardName['Amulet'].singular = "보호부적";
LANGUAGE.getCardName['Artificer'].singular = "기능공";
LANGUAGE.getCardName['Bridge Troll'].singular = "다리괴수";
LANGUAGE.getCardName['Caravan Guard'].singular = "대상의 호위";
LANGUAGE.getCardName[CardNames.COIN_OF_THE_REALM].singular = "왕국금화";
LANGUAGE.getCardName[CardNames.DISTANT_LANDS].singular = "먼 땅";
LANGUAGE.getCardName['Dungeon'].singular = "지하 감옥";
LANGUAGE.getCardName['Duplicate'].singular = "복제품";
LANGUAGE.getCardName['Gear'].singular = "장비";
LANGUAGE.getCardName['Giant'].singular = "거인";
LANGUAGE.getCardName['Guide'].singular = "안내인";
LANGUAGE.getCardName['Haunted Woods'].singular = "유령의 숲";
LANGUAGE.getCardName['Hireling'].singular = "야영자";
LANGUAGE.getCardName['Lost City'].singular = "잃어버린 도시";
LANGUAGE.getCardName['Magpie'].singular = "까치";
LANGUAGE.getCardName['Messenger'].singular = "심부름꾼";
LANGUAGE.getCardName['Miser'].singular = "구두쇠";
LANGUAGE.getCardName['Port'].singular = "항구";
LANGUAGE.getCardName['Ranger'].singular = "유격병";
LANGUAGE.getCardName['Ratcatcher'].singular = "쥐잡이꾼";
LANGUAGE.getCardName['Raze'].singular = "붕괴";
LANGUAGE.getCardName['Relic'].singular = "유물";
LANGUAGE.getCardName['Royal Carriage'].singular = "성가";
LANGUAGE.getCardName['Storyteller'].singular = "이야기꾼";
LANGUAGE.getCardName['Swamp Hag'].singular = "늪의 마녀";
LANGUAGE.getCardName['Transmogrify'].singular = "변용";
LANGUAGE.getCardName['Treasure Trove'].singular = "묻혀있던 보물";
LANGUAGE.getCardName['Wine Merchant'].singular = "와인상인";
LANGUAGE.getCardName['Peasant'].singular = "농부";
LANGUAGE.getCardName['Soldier'].singular = "병사";
LANGUAGE.getCardName['Fugitive'].singular = "도망자";
LANGUAGE.getCardName['Disciple'].singular = "제자";
LANGUAGE.getCardName['Teacher'].singular = "선생";
LANGUAGE.getCardName['Page'].singular = "견습 기사";
LANGUAGE.getCardName['Treasure Hunter'].singular = "보물 사냥꾼";
LANGUAGE.getCardName['Warrior'].singular = "전사";
LANGUAGE.getCardName['Hero'].singular = "영웅";
LANGUAGE.getCardName['Champion'].singular = "챔피언";
LANGUAGE.getCardName['Alms'].singular = "구호품";
LANGUAGE.getCardName['Ball'].singular = "무도회";
LANGUAGE.getCardName['Bonfire'].singular = "모닥불";
LANGUAGE.getCardName['Borrow'].singular = "차용";
LANGUAGE.getCardName['Expedition'].singular = "원정";
LANGUAGE.getCardName['Ferry'].singular = "나룻배";
LANGUAGE.getCardName['Inheritance'].singular = "상속";
LANGUAGE.getCardName['Lost Arts'].singular = "잊혀진 기술";
LANGUAGE.getCardName['Mission'].singular = "사명";
LANGUAGE.getCardName['Pathfinding'].singular = "길잡이";
LANGUAGE.getCardName['Pilgrimage'].singular = "순례";
LANGUAGE.getCardName['Plan'].singular = "계획";
LANGUAGE.getCardName['Quest'].singular = "지령";
LANGUAGE.getCardName['Raid'].singular = "습격";
LANGUAGE.getCardName['Save'].singular = "절약";
LANGUAGE.getCardName['Scouting Party'].singular = "척후 부대";
LANGUAGE.getCardName['Seaway'].singular = "해로";
LANGUAGE.getCardName['Travelling Fair'].singular = "유랑단";
LANGUAGE.getCardName['Trade'].singular = "교역";
LANGUAGE.getCardName['Training'].singular = "훈련";




LANGUAGE.getCardText['Amulet'] = '<div style="position:relative; top:8px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">이번 턴과 다음 턴을 시작할 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">하나를 선택할 수 있다:  <div style="display: inline; font-weight: bold;">+  </div>      ;</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">패의 카드 한 장을 폐기한다;</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">은 카드 한 장을 얻는다;</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:34px; display: inline;left:233px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText['Artificer'] = '<div style="font-weight: bold;"><div style="line-height:24px;"><div style="display:inline;"><div style="display:inline; font-size:27px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:27px;">+액션 1번</div></div></br><div style="display:inline;"><div style="display:inline; font-size:27px;"><div style="position: relative; left:-12px;top:5px;">+</div></div></div></br></div></div><div style="position:relative; top:-15px;"><div style="line-height:15px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">패에서 원하는 만큼 카드를 버린다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">버린 카드 한 장 당         로 </div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">계산하여 가격을 합한</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">카드를 얻어, 그 카드를 자신의</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">덱 맨 위에 올린다.</div></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:53.5px; display: inline;left:139px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.15); top:102px; display: inline;left:200px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText['Bridge Troll'] = '<div style="position:relative; top:10px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">다른 플레이어들은</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;"><div style="display:inline; font-weight:bold;">-</div>      토큰을 얻는다</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;">지금과 다음 턴에: <div style="display: inline; font-weight: bold;">+구매 1번</div>.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:18px;"></div><div style="position:relative; top:5px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">이 카드가 플레이 공간에 있을 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">자신의 턴에 모든 카드의</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">가격은       낮아진다.</div></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:34px; display: inline;left:68px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:138px; display: inline;left:120px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText['Caravan Guard'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div></div><div style="position:relative; top:0px;"><div style="line-height:17.5px;"><div style="display:inline;"><div style="display:inline; font-size:15px;">다음 턴에,    <div style="display: inline; font-weight: bold;">+</div>      .</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:2px;"></div><div style="position:relative; top:0px;"><div style="line-height:17.5px;"><div style="display:inline;"><div style="display:inline; font-size:15px;">다른 플레이어가 공격 카드를 사용했을 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;">손에서 이 카드를 사용할 수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;"><div style="display: inline; font-style: italic;"> (당신의 턴에 사용되지 않았을 경우,  </div></div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;"><div style="display: inline; font-style: italic;"><div style="display: inline; font-weight: bold;">+액션 1번</div>   은 하지 않는다.)</div></div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.17); top:58px; display: inline;left:175px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';

LANGUAGE.getCardText[CardNames.COIN_OF_THE_REALM] = '<div style="position:relative; top:42px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">이 카드를 사용한 뒤,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">술집 매트 위에 올려 놓는다.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:46px;"></div><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">액션 카드의 효과를 끝낸 뒤,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">호출할 수 있다. 호출하면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;"><div style="display: inline; font-weight: bold;">+액션 2번</div>.</div></div></br></div><div class="card-text-coin-icon" style="transform:scale(0.5); top:-18px; display: inline;left:110px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText[CardNames.DISTANT_LANDS] = '<div style="position:relative; top:0px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">이 카드를 술집 매트</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;"> 위에 올려 놓는다.</div></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:18px;"></div><div style="position:relative; top:5px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">점수 계산시, 술집 매트 위에</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">있을 경우,     </div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">(아니면,            ).</div></div></br></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.18); top:106px;left:188px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">4</div></div><div class="card-text-vp-icon"></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.18); top:130px;left:159px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">0</div></div><div class="card-text-vp-icon"></div></div>';
LANGUAGE.getCardText['Dungeon'] = '<div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이번 턴, 그리고 다음 턴을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">시작 할 때: <div style="display: inline; font-weight: bold;">+카드 2장</div>, 그리고</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">카드 2장을 버린다.</div></div></br></div></div>';
LANGUAGE.getCardText['Duplicate'] = '<div style="position:relative; top:0px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">이 카드를 술집 매트 위에 놓는다.</div></div></br></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:18px;"></div><div style="position:relative; top:3px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">       이하의 카드를 얻을 경우,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 부르는 것으로</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">그 카드와 같은 카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">1장을 얻을 수 있다.</div></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:50px; display: inline;left:10px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">6</div></div></div>';

LANGUAGE.getCardText['Gear'] = '<div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 2장</div></div></br></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:20.5px;">손패에서 카드 2장까지</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20.5px;">뒤집어서 따로 놓는다. </div></div></br><div style="display:inline;"><div style="display:inline; font-size:20.5px;">다음 턴을 시작할 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20.5px;">그 카드를 손패에 넣는다.</div></div></br></div></div>';
LANGUAGE.getCardText['Giant'] = '<div style="position:relative; top:5px;"><div style="line-height:18.5px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">여행 토큰을 뒤집는다. (앞면으로</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;"> 게임시작) 그후, 토큰이 뒷면</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">이라면 <div style="display: inline; font-weight: bold;">+</div>        , 앞면이라면 <div style="display: inline; font-weight: bold;">+</div>        .</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">다른 플레이어들은 자신의 덱</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">맨 위에 있는 카드 1장을 공개한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:14.5px;">가격이      에서       까지의 카드라면 폐기하고,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;">아니면, 버리고 저주 카드를 한 장 얻는다. </div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:50px; display: inline;left:95px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:50px; display: inline;left:222px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">5</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.16); top:119px; display: inline;left:43px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.16); top:119px; display: inline;left:95px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">6</div></div></div>';
LANGUAGE.getCardText['Guide'] = '<div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div><div style="position:relative; top:-5px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">이 카드를 술집 매트위에 올린다.</div></div></br></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:1px;"></div><div style="position:relative; top:2px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">자신의 턴을 시작할 때, 이 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">부를 수 있다. 그러면, 패의 모든</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">카드를 버리고 카드 5장을 뽑는다.</div></div></br></div></div>';
LANGUAGE.getCardText['Haunted Woods'] = '<div style="position:relative; top:5px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">다음 턴까지, 카드를 구매한 다른</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">플레이어는 턴이 끝날 때 손패를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">덱 맨 위에 원하는 순서대로</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;"> 올려 놓아야 한다. </div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">다음 자신의 턴을 시작할 때,</div></div></div></div><div style="position:relative; top:10px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:26px;">+카드 3장</div></div></br></div></div>';

LANGUAGE.getCardText['Hireling'] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">게임 플레이 동안 자신의</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">턴이 시작할때마다</div></div></br></div></div><div style="position:relative; top:15px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br></div></div><div style="position:relative; top:12px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-style: italic;">(이 카드는 게임 동안 남는다.)</div></div></div></br></div></div>';
LANGUAGE.getCardText['Lost City'] = '<div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 2장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 2번</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:13px;"></div><div style="position:relative; top:8px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 얻었을 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">다른 플레이어들은 <div style="display:inline; font-weight:bold;">+카드 1장</div></div></div></br></div></div>';
LANGUAGE.getCardText['Magpie'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div></div><div style="position:relative; top:0px;"><div style="line-height:21px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">자신의 덱 맨 위의 카드를 공개한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">그 카드가 재물 카드라면 패에 넣는다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">액션이나 승점 카드라면</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">까치를 한 장 얻는다.</div></div></br></div></div>';
LANGUAGE.getCardText['Messenger'] = '<div style="font-weight: bold;"><div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">+구매 1번</div></div></br><div style="display:inline;"><div style="display:inline; font-size:26px;"><div style="position: relative; left:-14px;top:1px;">+</div></div></div></br></div></div><div style="position:relative; top:-27px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18.5px;">자신의 덱을 자신의 버린 카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18.5px;">더미에 놓을 수 있다.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:-22px;"></div><div style="position:relative; top:-3px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">이번 턴에 이 카드를 처음으로 구매하면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">       이하의 카드 한 장을 얻고 다른</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">플레이어 모두 그 카드를 한 장 씩 얻는다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.23); top:26px; display: inline;left:137px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.17); top:124px; display: inline;left:24px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div>';

LANGUAGE.getCardText['Miser'] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">하나를 선택한다: 손패에서</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">술집 매트로 동을 1장 올려 놓는다;</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">자신의 술집 매트 위</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">동 카드 한 장 마다 <div style="display: inline; font-weight: bold;">+</div>       ;</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:87px; display: inline;left:205px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText['Port'] = '<div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 2번</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:7px;"></div><div style="position:relative; top:7px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 구매했을 경우,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">항구 한 장을 얻는다.</div></div></br></div></div>';
LANGUAGE.getCardText['Ranger'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+구매 1번</div></div></br></div></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">여행 토큰을 뒤집는다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">(앞면으로 시작) 토큰이 </div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">앞면이라면,  <div style="display: inline; font-weight: bold;">+카드 5장</div>.</div></div></br></div></div>';
LANGUAGE.getCardText['Ratcatcher'] = '<div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div><div style="position:relative; top:-5px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">이 카드를 술집 매트 위에 올린다.</div></div></br></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:1px;"></div><div style="position:relative; top:2px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">턴을 시작할 때, 이 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">부르는 것으로 패의 카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">한 장을 폐기 할 수 있다.</div></div></br></div></div>';

LANGUAGE.getCardText['Raze'] = '<div style="position:relative; top:5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div><div style="position:relative; top:10px;"><div style="line-height:21px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">이 카드 혹은 다른 카드 한 장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">손에서 폐기한다. 폐기된 카드의</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">가격만큼 카드를 덱 위에서 확인한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">한 장을 패에 넣고 나머지는 버린다.</div></div></div></div>';
LANGUAGE.getCardText['Relic'] = '<div style="position: relative; left:-40px;top:-30px;"><div class="card-text-coin-icon" style="transform:scale(0.55); top:0px; display: inline;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div></div><div style="position:relative; top:40px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:17.5px;">이 카드를 플레이 할 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17.5px;">다른 플레이어들은 자신의</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17.5px;"><div style="display:inline; font-weight:bold;">-1 카드 토큰</div>을 덱 위에 올려 놓는다.</div></div></br></div></div>';

LANGUAGE.getCardText['Royal Carriage'] = '<div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div><div style="position:relative; top:-3px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">이 카드를 술집 매트 위에 올린다.</div></div></br></div><div class="horizontal-line" style="width:200px; height:3px;"></div><div style="position:relative; top:0px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">액션카드를 사용한 직후, 만약 사용한</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">액션 카드가 아직 플레이 중이라면</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">이 카드를 부르는 것으로 그 카드의</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">액션을 한번 더 할 수 있다.</div></div></br></div></div>';
LANGUAGE.getCardText['Storyteller'] = '<div style="font-weight: bold;"><div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;"><div style="position: relative; left:-14px;top:5px;">+</div></div></div></br></div></div><div style="position:relative; top:-20px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">최대 3장까지의 재물 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">플레이한다. 재물 카드의</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">      를 합한 만큼 카드를 뽑는다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">(이 카드의       를 포함한다.)</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.23); top:30px; display: inline;left:137px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:105px; display: inline;left:5px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;"></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:128px; display: inline;left:120px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText['Swamp Hag'] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">다음 당신의 턴까지, 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">구매한 플레이어는 저주</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">카드를 1장 얻는다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">다음 자신의 턴을 시작할 때,</div></div></br></div></div><div style="position:relative; top:5px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+     </div></div></br></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.25); top:102px; display: inline;left:133px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div>';

LANGUAGE.getCardText['Transmogrify'] = '<div style="font-weight: bold;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div><div style="position:relative; top:-5px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">이 카드를 술집 매트 위에 올린다.</div></div></br></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:1px;"></div><div style="position:relative; top:5px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:15.5px;">자신의 턴을 시작할 때, 이 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15.5px;">부르는 것으로 패의 카드 1장을 폐기하고</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15.5px;">폐기한 카드보다 가격이 최대        높은</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15.5px;">카드 한장을 얻어서 손패에 넣는다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.17); top:112px; display: inline;left:217px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText['Treasure Trove'] = '<div style="position: relative; left:-35px;top:-30px;"><div class="card-text-coin-icon" style="transform:scale(0.5); top:0px; display: inline;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div></div><div style="position:relative; top:40px;"><div style="line-height:24px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 플레이할 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">금과 동을 한 장씩 얻는다.</div></div></br></div></div>';
LANGUAGE.getCardText['Wine Merchant'] = '<div style="font-weight: bold;"><div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">+구매 1번</div></div></br><div style="display:inline;"><div style="display:inline; font-size:26px;"><div style="position: relative; left:-12px;top:1px;">+</div></div></div></br></div></div><div style="position:relative; top:-23px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">이 카드를 술집 매트 위에 올린다.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:-14px;"></div><div style="position:relative; top:4px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">구입 단계를 마치고 사용 가능한</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">재화가       이상 남았다면, 이 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">술집 매트에서 버릴 수 있다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.22); top:28px; display: inline;left:140px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:117px; display: inline;left:64px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';

LANGUAGE.getCardText['Peasant'] = '<div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+구매 1번</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;"><div style="position: relative; left:-14px;top:1px;">+</div></div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:-15px;"></div><div style="position:relative; top:8px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">사용한 후 버려지면</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">병사 카드로 바꿀 수 있다.</div></div></br></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.23); top:29px; display: inline;left:137px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText['Soldier'] = '<div style="font-weight: bold;"><div style="line-height:24px;"><div style="display:inline;"><div style="display:inline; font-size:24px;"><div style="position: relative; left:-12px;top:5px;">+</div></div></div></br></div></div><div style="position:relative; top:-24px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">자신이 사용한 공격 카드의 수만큼</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">추가로 <div style="display: inline; font-weight: bold;">+</div>       . 패가 4장 이상인</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">상대 플레이어는 카드를 한 장 버린다.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:-20px;"></div><div style="position:relative; top:0px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">사용한 후 버려지면 도망자 카드로</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">바꿀 수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;"><div style="display: inline; font-style: italic;">(이 카드는 공급처의 카드가 아닙니다.)</div></div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.23); top:2px; display: inline;left:140px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:47px; display: inline;left:97px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText['Fugitive'] = '<div style="font-weight: bold;"><div style="line-height:24px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">+카드 2장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:26px;">+액션 1번</div></div></br></div></div><div style="position:relative; top:-5px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">카드 한 장을 버린다.</div></div></br></div><div class="horizontal-line" style="width:200px; height:3px;"></div><div style="position:relative; top:5px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">사용한 후 버려지면</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">제자 카드로 바꿀 수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;"><div style="display: inline; font-style: italic;">(이 카드는 공급처의 카드가 아닙니다.)</div></div></div></br></div></div>';
LANGUAGE.getCardText['Disciple'] = '<div style="position:relative; top:5px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">패에서 액션 카드 한 장을 두 번 사용</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">할 수 있다. 사용한 카드를 한 장 얻는다.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:20px;"></div><div style="position:relative; top:10px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">사용한 후 버려지면</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">선생 카드로 바꿀 수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;"><div style="display: inline; font-style: italic;">(이 카드는 공급처의 카드가 아닙니다.)</div></div></div></br></div></div>';
LANGUAGE.getCardText['Teacher'] = '<div style="position:relative; top:-5px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">이 카드를 술집 매트 위에 올린다.</div></div></br></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:-6px;"></div><div style="position:relative; top:0px;"><div style="line-height:17px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">당신의 턴을 시작할 때, 이 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">불러올 수 있다. 그러면 <div style="display: inline; font-weight: bold;">+카드 1장</div>, </div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;"><div style="display: inline; font-weight: bold;">+액션 1번, +구매 1번, +      </div>토큰 중</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">하나를 당신의 토큰이 없는 액션카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">공급처 한곳에 올린다. </div><div style="display:inline; font-size:13px;">(당신이 그 공급처의</div></div></br><div style="display:inline;"><div style="display:inline; font-size:13px;">카드를 사용하면 해당 보너스를 받는다.)</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;"><div style="display: inline; font-style: italic;">(이 카드는 공급처의 카드가 아닙니다.)</div></div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:67px; display: inline;left:193px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';

LANGUAGE.getCardText['Page'] = '<div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:13px;"></div><div style="position:relative; top:8px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">사용한 후 버려지면</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">보물 사냥꾼 카드로 바꿀 수 있다.</div></div></br></br></div></div>';
LANGUAGE.getCardText['Treasure Hunter'] = '<div style="font-weight: bold;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">+액션 1번</div></div></br><div style="display:inline;"><div style="display:inline; font-size:26px;"><div style="position: relative; left:-12px;top:5px;">+</div></div></div></br></div></div><div style="position:relative; top:-20px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18.5px;">당신의 오른쪽 플레이어가 턴 동안</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">얻은 카드 수만큼 은을 얻는다.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:-12px;"></div><div style="position:relative; top:0px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">사용한 후 버려지면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">전사 카드로 바꿀 수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;"><div style="display: inline; font-style: italic;">(이 카드는 공급처의 카드가 아닙니다.)</div></div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.21); top:25px; display: inline;left:140px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText['Warrior'] = '<div style="position:relative; top:2px; font-weight: bold;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">+카드 2장</div></div></br></div></div><div style="position:relative; top:-2px;"><div style="line-height:17px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">당신이 플레이한 (이 카드를 포함)</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">여행자 카드의 수만큼 다른 플레이어들은</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">자신의 덱에서 카드를 버린다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">그 중, 가격이      또는      카드는 폐기한다.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;"></div><div style="position:relative; top:0px;"><div style="line-height:16px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">사용한 후 버려지면</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">영웅 카드로 바꿀 수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;"><div style="display: inline; font-style: italic;">(이 카드는 공급처의 카드가 아닙니다.)</div></div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.16); top:85px; display: inline;left:92px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.16); top:85px; display: inline;left:147px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div>';
LANGUAGE.getCardText['Hero'] = '<div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;"><div style="position: relative; left:-12px;top:5px;">+</div></div></div></br></div></div><div style="position:relative; top:-24px;"><div style="display:inline;"><div style="display:inline; font-size:18.5px;">원하는 재물 카드를 한 장 얻는다.</div></div></br></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:-12px;"></div><div style="position:relative; top:7px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:18.3px;">사용한 후 버려지면</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18.3px;">챔피언 카드로 바꿀 수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;"><div style="display: inline; font-style: italic;">(이 카드는 공급처의 카드가 아닙니다.)</div></div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.25); top:1px; display: inline;left:137px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText['Champion'] = '<div style="display:inline; font-size:28px;"><div style="font-weight: bold;"><div style="display:inline;">+액션 1번</div></br></div></div><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">남은 게임동안 다른 플레이어가</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">공격 카드를 사용했을 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">당신은 효과를 받지 않는다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">액션 카드를 사용하면,<div style="display: inline; font-weight: bold;">+액션 1번</div>.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px; font-weight:bold;"><div style="display: inline; font-style: italic;">(이 카드는 게임에 계속 남는다.)</div></div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;"><div style="display: inline; font-style: italic;">(이 카드는 공급처의 카드가 아닙니다.)</div></div></div></br></div>';

LANGUAGE.getCardText['Alms'] = '<div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">한 턴에 한 번: 플레이 영역에 재물 카드가 없다면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">       까지의 카드 한 장을 얻는다.</div></div></br></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:30px; display: inline;left:80px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div>';
LANGUAGE.getCardText['Ball'] = '<div style="display:inline;"><div style="display:inline; font-size:17px;">   -       토큰을 얻는다.<div class="card-text-coin-icon" style="transform:scale(0.18); top:7px; display: inline;left:25px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>가격이       이하인 카드를 2장 얻는다<div class="card-text-coin-icon" style="transform:scale(0.18); top:7px; display: inline;left:215px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div>.</div></div></br>';
LANGUAGE.getCardText['Bonfire'] = '<div style="display:inline;"><div style="display:inline; font-size:20px;">플레이 영역에 있는 카드를 2장까지 폐기힌다.</div></div></br>';
LANGUAGE.getCardText['Borrow'] = '<div style="position:relative; top:10px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">한 턴에 한 번: <div style="display: inline; font-weight: bold;">+구매 1번</div>. -1 카드 토큰이 덱 위에 없다면,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18.5px;">-1 카드 토큰을 덱 위에 두고, <div style="display: inline; font-weight: bold;">+</div>       .</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:34px; display: inline;left:325px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText['Expedition'] = '<div style="display:inline;"><div style="display:inline; font-size:22px;">정리 단계 이후, 손패에 <div style="display:inline; font-weight:bold;">+카드 2장</div></div></div></br>';
LANGUAGE.getCardText['Ferry'] = '<div style="position:relative; top:7px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:17px;"> -      토큰을 액션 카드 공급처 중 하나에 놓는다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">(그 공급처의 카드는 당신의 턴 중에 -        .)</div></div></br></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:2px; display: inline;left:55px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:28px; display: inline;left:344px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div></div>';

LANGUAGE.getCardText['Inheritance'] = '<div style="line-height:17px;"><div style="display:inline;"><div style="display:inline; font-size:14px;">한 게임에 한 번만: 공급처에서 가격이       까지인 (승점 카드가 아닌)</div></div></br><div style="display:inline;"><div style="display:inline; font-size:14px;">액션 카드를 1장 따로 둔다. 그 위에 사유지 토큰을 이동시킨다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:14px;">(당신의 사유지는 그 카드의 능력과 타입을 얻는다.)</div></div></br></div><div class="card-text-coin-icon" style="transform:scale(0.16); top:3px; display: inline;left:245px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div>';
LANGUAGE.getCardText['Lost Arts'] = '<div style="position:relative; top:10px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">당신의 +1 액션 토큰을 액션 카드 공급처 중 하나에 올린다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:12px;">(+1 액션 토큰이 놓여있는 액션 카드 더미의 카드를 플레이할 경우, <div style="display: inline; font-weight: bold;">+액션 1번</div>.)</div></div></br></div></div>';
LANGUAGE.getCardText['Mission'] = '<div style="position:relative; top:8px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">한 턴에 한 번: 이전 턴이 당신의 턴이 아닐 경우,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">추가 턴을 얻는다. 추가 턴에는 카드를 구입할 수 없다.</div></div></br></div></div>';
LANGUAGE.getCardText['Pathfinding'] = '<div style="position:relative; top:8px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:17.5px;">+1 카드 토큰을 액션 카드 공급처 하나 위에 올린다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17.5px;">(당신이 +1 카드 토큰이 있는 카드를 사용하면, <div style="display: inline; font-weight: bold;">+카드 1장</div>.)</div></div></br></div></div>';

LANGUAGE.getCardText['Pilgrimage'] = '<div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">한 턴에 한 번: 당신은 여행 토큰을 뒤집는다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">(앞면으로 게임을 시작한다.) 앞면이라면 플레이한 카드 중,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">최대 3장까지 다른 이름의 카드를 선택하여 얻는다.</div></div></br></div>';
LANGUAGE.getCardText['Plan'] = '<div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:18.5px;">폐기 토큰을 액션 카드 공급처 중 하나 위에 올린다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18.5px;">(폐기 토큰이 놓여 있는 카드를 구매할 경우,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18.5px;">손패에서 카드 한 장을 폐기할 수 있다.)</div></div></br></div>';
LANGUAGE.getCardText['Quest'] = '<div style="display:inline;"><div style="display:inline; font-size:20px;">공격 카드 1장, 저주 카드 2장 또는 카드 6장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">버리면, 금을 하나 얻는다.</div></div></br>';
LANGUAGE.getCardText['Raid'] = '<div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">당신이 사용한 은 카드의 수만큼 은 카드를 얻는다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">다른 플레이어들은 자신의 덱 위에 -1 카드 토큰을 둔다.</div></div></br></div>';

LANGUAGE.getCardText['Save'] = '<div style="display:inline;"><div style="display:inline; font-size:17px;">한 턴에 한 번: <div style="display: inline; font-weight: bold;">+구매 1번</div>, 손패에서 카드를 1장 따로 둔다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">턴이 끝나고 손패를 뽑은 뒤에, 따로 둔 카드를 손패에 넣는다.</div></div></br>';
LANGUAGE.getCardText['Scouting Party'] = '<div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:22px;">+구매 1번</div></div></br></div></div><div style="position:relative; top:-7px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">자신의 덱 위, 5장의 카드를 본다. 3장을 버리고,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">나머지는 원하는 순서대로 덱 위에 올려놓는다.</div></div></br></div></div>';
LANGUAGE.getCardText['Seaway'] = '<div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">가격이      이하인 액션 카드를 얻는다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">얻은 액션카드의 공급처 위에 +1 구입 토큰을 둔다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">(+1 구입 토큰이 있는 카드를 사용하면, <div style="display: inline; font-weight: bold;">+구매 1번</div>.)</div></div></br></div><div class="card-text-coin-icon" style="transform:scale(0.16); top:3px; display: inline;left:128px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div>';
LANGUAGE.getCardText['Travelling Fair'] = '<div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:22px;">+구매 2번</div></div></br></div></div><div style="position:relative; top:-7px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">당신은 이번 턴에 카드를 얻을 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">얻은 카드를 덱 맨 위에 놓을 수 있다.</div></div></br></div></div>';

LANGUAGE.getCardText['Trade'] = '<div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">손패에서 2장까지 카드를 폐기힌다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">폐기한 카드의 수만큼 은 카드를 얻는다.</div></div></br></div>';
LANGUAGE.getCardText['Training'] = '<div style="position:relative; top:8px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">당신의 +      토큰을 액션카드 공급처 중 하나에 올린다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:14px;">(+      토큰이 놓여있는 액션 카드 공급처의 카드를 사용할 경우, <div style="display:inline; font-weight:bold;">+</div>        )</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:10px; display: inline;left:73px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.16); top:36px; display: inline;left:403px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.16); top:36px; display: inline;left:18px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
