translateName(LANGUAGE.getCardName[CardNames.POTION], '포션');
translateName(LANGUAGE.getCardName['Alchemist'], '연금술사');
translateName(LANGUAGE.getCardName['Apothecary'], '약제사');
translateName(LANGUAGE.getCardName['Apprentice'], '견습마법사');
translateName(LANGUAGE.getCardName['Familiar'], '사역마');
translateName(LANGUAGE.getCardName['Golem'], '골렘');
translateName(LANGUAGE.getCardName['Herbalist'], '약초상');
translateName(LANGUAGE.getCardName[CardNames.PHILOSOPHERS_STONE], '현자의 돌');
translateName(LANGUAGE.getCardName['Possession'], '지배 ');
translateName(LANGUAGE.getCardName['Scrying Pool'], '예언의 항아리');
translateName(LANGUAGE.getCardName['Transmute'], '변성');
translateName(LANGUAGE.getCardName['University'], '대학');
translateName(LANGUAGE.getCardName['Vineyard'], '포도원');


LANGUAGE.getCardText['Alchemist'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 2장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div></div><div style="position:relative; top:7px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">이번 차례에 포션을 사용했다면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 다시 덱 맨 위로</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">되돌릴 수 있습니다.</div></div></br></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:-96px;"></div>';
LANGUAGE.getCardText['Apothecary'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div></div><div style="position:relative; top:0px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">덱 맨 위의 4장의 카드를 공개합니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">공개된 동화와 포션은 패로 가져오고</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">나머지 카드들은 덱 맨 위에 원하는</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">순서대로 되돌려 놓습니다.</div></div></br></div></div>';
LANGUAGE.getCardText['Apprentice'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div></div><div style="position:relative; top:10px;"><div style="line-height:23px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">패에서 카드 한 장을 폐기합니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">폐기한 카드의</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">가격      당, <div style="display: inline; font-weight: bold;">+카드 1장</div>.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">가격에      있을 경우, <div style="display: inline; font-weight: bold;">+카드 2장</div></div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:94px; display: inline;left:95px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div class="card-text-potion-icon" style="transform:scale(0.18); top:123px; display: inline;left:85px;"></div>';
LANGUAGE.getCardText['Familiar'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">다른 플레이어들은</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">저주 카드 1장을 얻습니다.</div></div></br></div></div>';

LANGUAGE.getCardText['Golem'] = '<div style="position:relative; top:7px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">골렘 카드를 제외한 다른 액션 카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">2장이 나올 때까지 카드를 공개합니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">나머지 카드들은 버리고 공개된 카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">2장을 원하는 순서대로 사용합니다.</div></div></br></br></div></div>';
LANGUAGE.getCardText['Herbalist'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+구매 1번</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+    </div></div></br></div></div></div><div style="position:relative; top:10px;"><div style="line-height:21.5px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">이 카드가 사용된 후, 버려질 때</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">이번 차례에 사용한 재물 카드 중</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">한 장을 골라 덱 맨 위로</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">되돌릴 수 있습니다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.22); top:29px; display: inline;left:138px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:-93px;"></div>';
LANGUAGE.getCardText[CardNames.PHILOSOPHERS_STONE] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">덱의 수와 버린 카드의 개수를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;">합한 수에 5를 나눈만큼</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;"><div style="display:inline; font-weight:bold;">+</div></div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;">(소수점은 내림으로 적용)</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:59px; display: inline;left:150px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText['Possession'] = '<div style="position:relative; top:25px;"><div style="line-height:17px;"><div style="display:inline;"><div style="display:inline; font-size:14px;">다음 플레이어의 차례를 당신이 대신 합니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:14px;">단, 당신이 얻은 모든 카드와          은</div></div></br><div style="display:inline;"><div style="display:inline; font-size:14px;">당신이 대신 얻고, 당신이 폐기한 모든 카드는</div></div></br><div style="display:inline;"><div style="display:inline; font-size:14px;">다음 플레이어의 버린 카드 더미로 옮깁니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:14px;">이후, 다음 플레이어는 자신의 턴을 한번 더</div></div></br><div style="display:inline;"><div style="display:inline; font-size:14px;">정상적으로 진행합니다.</div></div></br></br></br></div></div><div class="card-text-debt-icon" style="transform:scale(0.16); top:47px; display: inline;left:215px;"><div class="card-text-debt-text-container" style="display:inline;"><div class="card-text-debt-text" style="display:inline; top:48px;"></div></div></div>';

LANGUAGE.getCardText['Scrying Pool'] = '<div style="position:relative; top:4px;"><div style="font-weight: bold;"><div style="line-height:23px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div></div><div style="position:relative; top:6px;"><div style="line-height:16px;"><div style="display:inline;"><div style="display:inline; font-size:15px;">(당신을 포함한) 모든 플레이어는 덱 위의</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;">카드 한 장을 공개하고, 공개된 카드들을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;">각각 다시 덱으로 되돌릴지 버릴지 당신이</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;">선택합니다. 이후 액션 카드가 아닌 카드가</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;">나올 때 까지 당신의 덱 맨 위의 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;">계속 공개합니다. 당신의 공개된 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;">전부 손패로 가져옵니다.</div></div></div></div>';
LANGUAGE.getCardText['Transmute'] = '<div style="position:relative; top:7px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">손패에서 카드 1장을 폐기합니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">그 카드가...</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">액션 카드라면 공작령 1장을 얻습니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">재화 카드라면 변성 1장을 얻습니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">승점 카드라면 금 1장을 얻습니다.</div></div></br></div></div>';
LANGUAGE.getCardText['University'] = '<div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 2번</div></div></br></div></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">가격이      이하인 액션 카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">1장을 얻을 수 있습니다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:38px; display: inline;left:85px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">5</div></div></div>';
LANGUAGE.getCardText['Vineyard'] = '<div style="position:relative; top:10px;"><div style="line-height:25px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">자신이 가진 액션카드 3장 당</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">              (소수점 버림).</div></div></br></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.2); top:40px;left:84px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">1</div></div><div class="card-text-vp-icon"></div></div>';