LANGUAGE.getCardName[CardNames.CURSE].singular = '저주';
LANGUAGE.getCardName[CardNames.COPPER].singular = '동';
LANGUAGE.getCardName[CardNames.SILVER].singular = '은';
LANGUAGE.getCardName[CardNames.GOLD].singular = '금';
LANGUAGE.getCardName[CardNames.ESTATE].singular = '사유지';
LANGUAGE.getCardName[CardNames.DUCHY].singular = '공작령';
LANGUAGE.getCardName[CardNames.PROVINCE].singular = '속주';
LANGUAGE.getCardName[CardNames.ARTISAN].singular = '장인';
LANGUAGE.getCardName[CardNames.BANDIT].singular = '노상강도';
LANGUAGE.getCardName[CardNames.BUREAUCRAT].singular = '관료';
LANGUAGE.getCardName[CardNames.CELLAR].singular = '저장고';
LANGUAGE.getCardName[CardNames.CHAPEL].singular = '예배당';
LANGUAGE.getCardName[CardNames.FESTIVAL].singular = '축제';
LANGUAGE.getCardName[CardNames.GARDENS].singular = '정원';
LANGUAGE.getCardName[CardNames.HARBINGER].singular = '선구자';
LANGUAGE.getCardName[CardNames.LABORATORY].singular = '실험실';
LANGUAGE.getCardName[CardNames.LIBRARY].singular = '도서관';
LANGUAGE.getCardName[CardNames.MARKET].singular = '시장';
LANGUAGE.getCardName[CardNames.MERCHANT].singular = '무역상';
LANGUAGE.getCardName[CardNames.MILITIA].singular = '민병대';
LANGUAGE.getCardName[CardNames.MINE].singular = '광산';
LANGUAGE.getCardName[CardNames.MOAT].singular = '해자';
LANGUAGE.getCardName[CardNames.MONEYLENDER].singular = '대금업자';
LANGUAGE.getCardName[CardNames.POACHER].singular = '밀렵꾼';
LANGUAGE.getCardName[CardNames.REMODEL].singular = '개조';
LANGUAGE.getCardName[CardNames.SENTRY].singular = '보초병';
LANGUAGE.getCardName[CardNames.SMITHY].singular = '대장장이';
LANGUAGE.getCardName[CardNames.VASSAL].singular = '봉신';
LANGUAGE.getCardName[CardNames.VILLAGE].singular = '마을';
LANGUAGE.getCardName[CardNames.WITCH].singular = '마녀';
LANGUAGE.getCardName[CardNames.WORKSHOP].singular = '작업장';
LANGUAGE.getCardName[CardNames.COUNCIL_ROOM].singular = '회의실';
LANGUAGE.getCardName[CardNames.THRONE_ROOM].singular = '알현실';


LANGUAGE.getCardText['Cellar'] = '<div style="position:relative; top:-7px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 액션 1번</div></div></br></div></div><div style="position:relative; top:3px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">카드를 원하는만큼 버림</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">+ 버린 카드 1장당 카드 1장</div></div></br></div></div>';
LANGUAGE.getCardText['Gardens'] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">덱의 카드 10장당 승점      </div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">(소수점 이하는 버림)</div></div></br></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.21); top:11px;left:250px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">1</div></div><div class="card-text-vp-icon"></div></div>';
LANGUAGE.getCardText['Moneylender'] = '<div style="position:relative; top:8px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">손의 동 카드 1장을 폐기</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">그렇게 할 경우 <div style="display: inline; font-weight: bold;">+</div>      .</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:34px; display: inline;left:208px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div>';
LANGUAGE.getCardText['Bandit'] = '<div style="position:relative; top:18px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">금 1장을 얻습니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">다른 플레이어는 각자의 덱</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">맨 위 2장을 공개해서 나온,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">동이 아닌 재물카드를 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">폐기하고 나머지는 버림</div></div></br></div></div>';
LANGUAGE.getCardText['Council Room'] = '<div style="position:relative; top:-30px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 4장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 구입 1번</div></div></br></div></div></div><div style="position:relative; top:-22px;"><div style="display:inline;"><div style="display:inline; font-size:21.3px;">다른 플레이어들은 각자</div></div></br><div style="display:inline; font-size:21.3px;">자기 덱에서 카드 1장을</div></br><div style="display:inline; font-size:21.3px;">손으로 가져감</div></br></br></div>';
LANGUAGE.getCardText['Festival'] = '<div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 액션 2번</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 구입 1번</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+    </div></div></br></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.22); top:53px; display: inline;left:139px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText['Moat'] = '<div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 2장</div></div></br></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:10px;"></div><div style="position:relative; top:9px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">다른 플레이어가 공격 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">사용할 때 손에서 이 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">를 공개할 수 있음. 공개하면</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">해당 공격 효과를 적용 안함</div></div></br></div></div>';
LANGUAGE.getCardText['Merchant'] = '<div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 액션 1번</div></div></br></div></div><div style="position:relative; top:10px;"><div style="line-height:21px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">이번 차례에 처음으로 은</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;">카드를 사용했다면 <div style="display: inline; font-weight: bold;">+</div>     .</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:93px; display: inline;left:222px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText['Vassal'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+      </div></div></br></div></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">당신의 덱 맨 위 카드를 버림</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">그것이 액션 카드라면, 액션</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">횟수 소모 없이 사용 가능</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.24); top:0px; display: inline;left:130px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText['Workshop'] = '<div style="position:relative; top:0px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">비용이     원 이하인</div></br><div style="display:inline; font-size:22px;">카드 1장을 얻음.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:0px; display: inline;left:116px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div>';
LANGUAGE.getCardText['Laboratory'] = '<div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 2장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 액션 1번</div></div></br></div></div></div>';
LANGUAGE.getCardText['Library'] = '<div style="position:relative; top:12px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">손에 있는 카드가 7장이</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">될 때까지 덱에서 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">가져옴. 이 과정에서 액션</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">카드는 따로 두고 가져오기</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">를 마친 후 모두 버림.</div></div></br></div></div>';
LANGUAGE.getCardText['Market'] = '<div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 액션 1번</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 구입 1번</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+    </div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.22); top:87px; display: inline;left:139px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText['Mine'] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">손에 있는 재물 1장을 폐기할</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">수 있음. 폐기한 카드보다</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">     원 높은 비용 한도 내에서</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">원하는 재물 카드 1장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">얻어 손에 듭니다.</div></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:56px; display: inline;left:10px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div>';
LANGUAGE.getCardText['Artisan'] = '<div style="position:relative; top:7px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">비용이      이하인 카드 한 장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">을 획득하여 손에 듭니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">손에서 카드 한장을 골라</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">덱 위로 올립니다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:2px; display: inline;left:76px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">5</div></div></div>';
LANGUAGE.getCardText['Chapel'] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">손에 있는 카드를 4장까지</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">폐기합니다.</div></div></br></div></div>';
LANGUAGE.getCardText['Harbinger'] = '<div style="position:relative; top:3px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 액션 1번</div></div></br></div></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:21.5px;">당신의 버린 카드더미를 본다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21.5px;">그 곳에 있는 카드 1장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21.5px;">당신의 덱 위에 둘 수 있다.</div></div></br></div></div>';
LANGUAGE.getCardText['Bureaucrat'] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">은 카드 1장을 얻어 덱 위에</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">놓습니다. 다른 플레이어들은</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">손에 있는 승점 카드 1장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">공개하고 공개한 승점카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">덱 맨 위에 놓습니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">(승점카드가 없으면 다 공개)</div></div></br></div></div>';
LANGUAGE.getCardText['Militia'] = '<div style="position:relative; top:-15px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+      </div></div></br></div></div><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">다른 플레이어들은 각자</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">손에 든 카드를 3장까지만</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">남기고 모두 버립니다.</div></div></br></div><div class="card-text-coin-icon" style="transform:scale(0.24); top:-15px; display: inline;left:130px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText['Poacher'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 액션 1번</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+    </div></div></br></div></div></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">비어있는 공급처 더미당</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">카드 1장을 버립니다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.22); top:58px; display: inline;left:138px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText['Throne Room'] = '<div style="position:relative; top:7px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">손에 있는 액션 카드 1장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">골라 2번 사용할 수 있음.</div></div></br></div></div>';
LANGUAGE.getCardText['Sentry'] = '<div style="position:relative; top:3px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 액션 1번</div></div></br></div></div></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:21.5px;">당신의 덱 위의 카드 2장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21.5px;">보고 원하는만큼 폐기하거나</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21.5px;">버린다. 나머지는 원하는</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21.5px;">순서대로 덱 위에 둔다.</div></div></br></div></div>';
LANGUAGE.getCardText['Witch'] = '<div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 2장</div></div></br></div></div><div style="position:relative; top:0px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">다른 플레이어들은 저주 카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;">1장을 얻습니다.</div></div></br></div></div>';
LANGUAGE.getCardText['Village'] = '<div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 액션 2번</div></div></br></div></div></div>';
LANGUAGE.getCardText['Remodel'] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">손에 있는 카드 1장을 폐기</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">합니다. 폐기한 카드보다</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">    원 높은 한도까지 원하는</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">카드 1장을 얻습니다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:56px; display: inline;left:10px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText['Smithy'] = '<div style="position:relative; top:-7px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 3장</div></div></br></div></div></div>';





// LANGUAGE.getCardName[CardNames.CASTLES].singular = '성';
// LANGUAGE.getCardName[CardNames.HUMBLE_CASTLE].singular = '초라한 성';
// LANGUAGE.getCardName[CardNames.CRUMBLING_CASTLE].singular = '붕괴된 성';
// LANGUAGE.getCardName[CardNames.SMALL_CASTLE].singular = '작은 성';
// LANGUAGE.getCardName[CardNames.HAUNTED_CASTLE].singular = '귀신 들린 성';
// LANGUAGE.getCardName[CardNames.OPULENT_CASTLE].singular = '호화로운 성';
// LANGUAGE.getCardName[CardNames.SPRAWLING_CASTLE].singular = '뻗어나가는 성';
// LANGUAGE.getCardName[CardNames.GRAND_CASTLE].singular = '거대한 성';
// LANGUAGE.getCardName[CardNames.KINGS_CASTLE].singular = '왕의 성';



// LANGUAGE.getCardText['Castles'] = '<div style="line-height:21px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">성 더미를 비싼 카드가</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;">바닥에 가도록 가격 순 정렬.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;">2인 게임에서는, 각 성 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;">1장씩만 사용한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;">성 더미의 맨 위 카드만</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;">공개되어 구매하거나</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;">얻을 수 있다.</div></div></br></div>';
// LANGUAGE.getCardText['Humble Castle'] = '<div class="horizontal-line" style="width:200px; height:3px;margin-top:47px;"></div><div style="position:relative; top:12px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">당신이 가진 성 한장 당</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">승점       점으로 취급.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.53); top:-35px; display: inline;left:110px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.2); top:86px;left:100px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">1</div></div><div class="card-text-vp-icon"></div></div>';
// LANGUAGE.getCardText['Crumbling Castle'] = '<div class="horizontal-line" style="width:200px; height:3px;margin-top:37px;"></div><div style="position:relative; top:9px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 얻거나 폐기할</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">경우 승점         과 은 카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">1장을 얻습니다.</div></div></br></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.53); top:-40px;left:130px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">1</div></div><div class="card-text-vp-icon"></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.19); top:73px;left:142px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">+1</div></div><div class="card-text-vp-icon"></div></div>';
// LANGUAGE.getCardText['Small Castle'] = '<div style="position:relative; top:-32px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드나 다른 성 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">패에서 폐기할 경우, 성</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">카드를 한 장 얻습니다.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:-25px;"></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.53); top:55px;left:130px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">2</div></div><div class="card-text-vp-icon"></div></div>';
// LANGUAGE.getCardText['Haunted Castle'] = '<div class="horizontal-line" style="width:200px; height:3px;margin-top:43px;"></div><div style="position:relative; top:4px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18.1px;">당신의 턴에 이 카드를 얻으면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18.1px;">금 카드를 얻고, 패가 5장 이상인</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18.1px;">다른 플레이어들은 패에서 2장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18.1px;">덱으로 되돌립니다.</div></div></br></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.53); top:-25px;left:130px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">2</div></div><div class="card-text-vp-icon"></div></div>';
// LANGUAGE.getCardText['Opulent Castle'] = '<div style="position:relative; top:-38px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">승점 카드를 원하는만큼</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">패에서 버립니다. 버린</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">카드 한 장당 <div style="display: inline; font-weight: bold;">+    </div></div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:-25px;"></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.53); top:55px;left:130px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">3</div></div><div class="card-text-vp-icon"></div></div><div class="card-text-coin-icon" style="transform:scale(0.22); top:10px; display: inline;left:203px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
// LANGUAGE.getCardText['Sprawling Castle'] = '<div class="horizontal-line" style="width:200px; height:3px;margin-top:47px;"></div><div style="position:relative; top:12px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 얻을 시, 공작령 한</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">장이나 사유지 세 장을 얻음.</div></div></br></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.53); top:-35px;left:130px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">4</div></div><div class="card-text-vp-icon"></div></div>';
// LANGUAGE.getCardText['Grand Castle'] = '<div class="horizontal-line" style="width:200px; height:3px;margin-top:43px;"></div><div style="position:relative; top:4px;"><div style="line-height:21px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">이 카드를 얻을 때 패를 공개,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;">패나 플레이 공간의 승점 카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;">한 장당 승점         .</div></div></br></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.53); top:-35px;left:130px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">5</div></div><div class="card-text-vp-icon"></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.18); top:98px;left:201px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">+1</div></div><div class="card-text-vp-icon"></div></div>';
// LANGUAGE.getCardText["King's Castle"] = '<div style="position:relative; top:12px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">당신이 가지고 있는 성 카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">한 장당 승점         .</div></div></br></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.19); top:37px;left:203px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">+2</div></div><div class="card-text-vp-icon"></div></div>';