// Copyright 2018 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Called when the user clicks on the browser action.
chrome.browserAction.onClicked.addListener(function (tab) {
	chrome.tabs.executeScript(tab.ib, {
		code: 
		`
		// 풍요의 뿔
		dictName['Fairgrounds'] = '박람회장';
		dictName['Farming Village'] = '농촌';
		dictName['Fortune Teller'] = '점술가';
		dictName['Hamlet'] = '작은 마을';
		dictName['Harvest'] = '수확';
		dictName['Horse Traders'] = '말 상인';
		dictName['Horn of Plenty'] = '풍요의 뿔';
		dictName['Hunting Party'] = '수렵단';
		dictName['Jester'] = '광대';
		dictName['Menagerie'] = '동물원 ';
		dictName['Remake'] = '개작';
		dictName['Tournament'] = '기사 무술 대회';
		dictName['Young Witch'] = '젊은 마녀';
		dictName['Bag of Gold'] = '금화 주머니';
		dictName['Princess'] = '공주';
		dictName['Trusty Steed'] = '명마';
		dictName['Diadem'] = '왕관';
		dictName['Followers'] = '추종자들';



		dictText['Fairgrounds'] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">덱에 있는 다른 이름의 카드 </div></div><br><div style="display:inline;"><div style="display:inline; font-size:21px;">5장마다 승점        를 얻습니다</div></div><br><div style="display:inline;"><div style="display:inline; font-size:21px;">(소숫점은 버립니다).</div></div><br></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.21); top:33px;left:150px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">2</div></div><div class="card-text-vp-icon"></div></div>';
		dictText['Farming Village'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 2번</div></div><br></div></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">액션 카드나 재물 카드가</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">나올 때까지 덱 위에서부터</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">카드를 공개합니다. 그 카드를 손에</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">넣고 다른 카드들은 버립니다.</div></div><br></div></div>';
		dictText['Fortune Teller'] = '<div style="position:relative; top:9px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:26px;">+     </div></div><br></div></div><div style="position:relative; top:-20px;"><div style="line-height:21.7px;"><div style="display:inline;"><div style="display:inline; font-size:15px;"></div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">다른 플레이어들은 승점 카드나</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">저주 카드가 나올 때 까지</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">덱 위에서부터 카드를 공개합니다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">나온 승점 또는 저주 카드를 덱 맨 위에 놓고</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">나머지 공개된 카드들은 버립니다.</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.25); top:9px; display: inline;left:135px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
		dictText['Hamlet'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div><br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div><br></div></div></div><div style="position:relative; top:3px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">카드 한장을 버리면;</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+액션 1번</div>.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">카드 한장을 버리면;</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+구매 1번</div>.</div></div><br></div></div>';
		dictText['Harvest'] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">덱 맨 위에서 카드를</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">4장 공개하고 버립니다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">공개된 카드 중 다른 이름의 카드</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">1장마다 <div style="display: inline; font-weight: bold;">   +</div></div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:85px; display: inline;left:200px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
		dictText['Horse Traders'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:21px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">+구매 1번</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">+ </div></div><br></div></div></div><div style="position:relative; top:0px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">카드 2장을 버린다.</div></div><br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:5px;"></div><div style="position:relative; top:-3px;"><div style="line-height:15px;"><div style="display:inline;"><div style="display:inline; font-size:15px;">다른 플레이어가 공격 카드를 사용했을 때,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">이 카드를 패에서 따로 둘 수 있습니다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">그렇게 하면 다음 당신의 턴을 시작할 때</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">이 카드를 패로 되돌리고<div style="display: inline; font-weight: bold;">+카드 1장</div></div></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:26px; display: inline;left:147px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div>';
		dictText['Horn of Plenty'] = '<div style="position:relative; top:0px;"><div style="line-height:13.7px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">이 카드를 플레이할 때,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">당신이 플레이중인 </div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">서로 다른 이름을 가진 카드 </div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">1장당      로 계산하여</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">(이 카드를 포함)</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">그만큼의 가치를 지닌 카드를</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">한 장 가져올 수 있습니다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">만약 가져온 카드가 승점 카드라면 </div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">이 카드를 폐기합니다.</div></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.15); top:65px; display: inline;left:110px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
		dictText['Hunting Party'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:27px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div><br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div><br></div></div></div><div style="position:relative; top:-3px;"><div style="line-height:20.5px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">당신의 덱을 손패와 겹치지 않는</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">카드가 나타날때까지 공개합니다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">손패와 겹치지 않는 카드를</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">당신의 패에 넣고, </div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">나머지는 버립니다.</div></div><br></div></div>';
		dictText['Jester'] = '<div style="position:relative; top:5px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+     </div></div><br></div></div></div><div style="position:relative; top:12px;"><div style="line-height:12.5px;"><div style="display:inline;"><div style="display:inline; font-size:14px;">다른 모든 플레이어들은</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">자신의 덱 위 카드 1장을 버린다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">그 카드가 승점 카드일 경우,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">그 플레이어는 저주 카드를 1장 얻는다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">승점 카드가 아니라면,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">버린 카드와 같은 카드를</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">상대방과 당신 중, 누가 얻을지 당신이 결정한다.</div></div><br><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.25); top:4px; display: inline;left:135px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
		dictText['Menagerie'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div><br></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">손패를 전부 공개합니다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">손패에 중복되는 </div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">카드가 없다면<div style="display: inline; font-weight: bold;">+카드 3장</div>.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">그 이외의 경우에는<div style="display: inline; font-weight: bold;">+카드 1장</div></div></div><br></div></div>';
		dictText['Remake'] = '<div style="position:relative; top:8px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이하의 행동을 두 번 한다 :</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">손에서 카드 한 장을 폐기하고</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">버린 카드보다 정확히</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">    비싼 카드를 가져온다.</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:83px; display: inline;left:15px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
		dictText['Tournament'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:20px;">+액션 1번</div></div><br></div></div><div style="position:relative; top:-3px;"><div style="line-height:12px;"><div style="display:inline;"><div style="display:inline; font-size:14px;">각 플레이어는 패에서</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">속주를 공개할 수 있습니다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">당신이 속주를 공개한 경우,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">공개한 카드를 버리고</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">상품 한 장 또는 공작령을 얻어</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">덱 맨 위에 둡니다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">아무도 속주를 공개하지 않았다면</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;"><div style="display: inline; font-weight: bold;">+카드 1장, </div><div style="display: inline; font-weight: bold;">+</div>         .</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.15); top:150px; display: inline;left:170px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
		dictText['Young Witch'] = '<div style="position:relative; top:-1px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:20px;">+카드 2장</div></div><br></div></div><div style="position:relative; top:-5px;"><div style="line-height:12px;"><div style="display:inline;"><div style="display:inline; font-size:14px;">카드를 두장 버립니다. 다른 플레이어들은 </div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">골칫거리 카드를 공개할 수 있습니다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">골칫거리 카드를 공개하지 않은 사람은</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">저주 1장을 얻습니다.</div></div></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:2px;"></div><div style="position:relative; top:0px;"><div style="line-height:12px;"><div style="display:inline;"><div style="display:inline; font-size:14px;">준비 단계 : 이 카드를 포함한 게임을 시작할 때 </div></div><br><div style="display:inline;"><div style="display:inline; font-size:13px;">비용     나     으로 구성된 추가 왕국 카드 더미를</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">공급처에 추가합니다. 그 카드 더미의 카드들이</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">바로 골칫거리 카드입니다.</div></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.12); top:124px; display: inline;left:34px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.12); top:124px; display: inline;left:65px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div>';		
		dictText['Bag of Gold'] = '<div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div><br></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">금 카드를 얻고, 그 카드를 플레이어의 </div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;"><div style="display: inline;">덱 맨 위에 올려 놓습니다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;"><div style="display: inline; font-style: italic;">(이 카드는 공급처의 카드가 아닙니다.)</div></div></div></div><br></div></div>';
		dictText['Princess'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+구매 1번</div></div><br></div></div><div style="position:relative; top:20px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">이 카드가 플레이공간에 있는 동안</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">카드의 가격은      낮아집니다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;"><div style="display: inline; font-style: italic;">(이 카드는 공급처의 카드가 아닙니다.)</div></div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:76px; display: inline;left:138px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:-67px;"></div>';
		dictText['Trusty Steed'] = '<div style="position:relative; top:7px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">두 가지 선택: <div style="display: inline; font-weight: bold;">+카드 2장</div>; </div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+액션 2번</div>; <div style="display: inline; font-weight: bold;">+</div>           </div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">은화 4장을 얻고, 덱을 모두 버린다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">*선택은 반드시 다른 </div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">두 개를 해야합니다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;"><div style="display: inline; font-style: italic;">(이 카드는 공급처의 카드가 아닙니다.)</div></div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:34px; display: inline;left:177px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
		dictText['Diadem'] = '<div style="position: relative; left:-35px;top:-20px;"><div class="card-text-coin-icon" style="transform:scale(0.5); top:0px; display: inline;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div></div><div style="position:relative; top:43px;"><div style="line-height:21.6px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">이 카드를 플레이할 때, 사용하지 않은</div></div><div style="display:inline;"><div style="display:inline; font-size:15px;">액션 횟수 한번에 1원씩 추가합니다.<div style="display: inline; font-weight: bold;">+</div></div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">(액션 카드가 아닌 액션 횟수입니다.)</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;"><div style="display: inline; font-style: italic;">(이 카드는 공급처의 카드가 아닙니다.)</div></div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.15); top:75px; display: inline;left:266px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
		dictText['Followers'] = '<div style="position:relative; top:3px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 2장</div></div><br></div></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">사유지를 얻습니다. 다른</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">플레이어들은 저주를 얻고</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">패가 3장이 되도록</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">카드를 버립니다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;"><div style="display: inline; font-style: italic;">(이 카드는 공급처의 카드가 아닙니다.)</div></div></div><br></div></div>';


		dictName['Prize'] = '상품';

		dictBottom['Bane'] = '골칫거리';
		dictBottom['Prize'] = '상품';
		dictBottom['Action - Attack - Prize'] = '액션 - 공격 -  상품';
		dictBottom['Action - Prize'] = '액션 - 상품';
		dictBottom['Treasure - Prize'] = '재물 - 상품';

		console.log("Load Cornucorpia info...");
		`
	});
});