// Copyright 2018 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Called when the user clicks on the browser action.
chrome.browserAction.onClicked.addListener(function (tab) {
	chrome.tabs.executeScript(tab.ib, {
		code: 
		`
		// 길드
		dictName['Advisor'] = '고문';
		dictName['Baker'] = '제빵사';
		dictName['Butcher'] = '도살자';
		dictName['Candlestick Maker'] = '촛대제작자';
		dictName['Doctor'] = '의사';
		dictName['Herald'] = '전령';
		dictName['Journeyman'] = '여행자';
		dictName['Masterpiece'] = '명작';
		dictName['Merchant Guild'] = '상인 조합';
		dictName['Plaza'] = '광장';
		dictName['Taxman'] = '세금징수원';
		dictName['Soothsayer'] = '예언자';
		dictName['Stonemason'] = '석공';


		dictText['Advisor'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div><br></div></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">카드 3장을 덱에서 공개하고</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">자신의 왼쪽 플레이어가</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">한장을 골라 버린다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">나머지 2장은 자신의</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">패에 넣는다.</div></div><br></div></div>';
		dictText['Baker'] = '<div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div><br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div><br><div style="display:inline;"><div style="display:inline; font-size:28px;">+코인 토큰 1개</div></div><br></div></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:4px;"></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">준비 단계: 각 플레이어는</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+동전 토큰 1개</div>.</div></div><br></div></div>';
		dictText['Butcher'] = '<div style="position:relative; top:3px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+동전 토큰 2개</div></div><br></div></div><div style="position:relative; top:2px;"><div style="line-height:16px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">손에 있는 카드 1장을</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">폐기할 수 있으며 폐기한</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">뒤에는 동전 토큰을 원하는</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">만큼 낼 수 있다. 폐기했다면,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">폐기한 카드의 가치와 낸 동전</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">토큰의 가치를 더한 값 이하의</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">가치를 지닌 카드 1장을 얻는다.</div></div></div></div>';
		dictText['Candlestick Maker'] = '<div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div><br><div style="display:inline;"><div style="display:inline; font-size:28px;">+구매 1번</div></div><br><div style="display:inline;"><div style="display:inline; font-size:28px;">+동전 토큰 1개</div></div><br></div></div></div>';

		dictText['Doctor'] = '<div style="position:relative; top:5px;"><div style="line-height:13px;"><div style="display:inline;"><div style="display:inline; font-size:15px;">카드의 이름을 말한다. 3장을 덱에서</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">공개하여 이름을 말한 카드가 나왔을</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">경우 폐기하고, 나머지 카드는</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">덱 위에 자기 맘대로 올려놓는다.</div></div></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:10px;"></div><div style="position:relative; top:0px;"><div style="line-height:13px;"><div style="display:inline;"><div style="display:inline; font-size:15px;">이 카드를 구입할 때, 돈을 추가로</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">지불할 수 있다. 추가로 지불한 돈</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">     원 마다 한번 덱 맨 위의 카드를</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">버릴지, 폐기할지, 덱에 되돌려</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">놓을지 결정할 수 있다.</div></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.15); top:123px; display: inline;left:28px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
		dictText['Herald'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">+카드 1장</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">+액션 1번</div></div><br></div></div></div><div style="position:relative; top:0px;"><div style="line-height:15px;"><div style="display:inline;"><div style="display:inline; font-size:15px;">덱 맨 위의 카드 한 장을 공개한다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">그 카드가 액션카드일 경우, 바로 사용한다.</div></div><br></div></div><div class="horizontal-line" style="width:200px; height:2px;"></div><div style="position:relative; top:5px;"><div style="line-height:16px;"><div style="display:inline;"><div style="display:inline; font-size:15px;">이 카드를 구입할 때, 돈을 추가로</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">지불할 수 있다. 추가로 지불한        당</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">한번씩 버린 카드 더미의 카드들 중</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">하나를 골라 자신의 덱 맨 위에 올릴 수 있다.</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.15); top:116px; display: inline;left:225px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
		dictText['Journeyman'] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:21.5px;">카드의 이름을 말한다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:21.5px;">말한 이름의 카드가 아닌</div></div><br><div style="display:inline;"><div style="display:inline; font-size:21.5px;">카드 3장이 나올 때까지</div></div><br><div style="display:inline;"><div style="display:inline; font-size:21.5px;">카드를 공개한 후 손에 든다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:21.5px;">나머지 카드는 버린다.</div></div><br></div></div>';
		dictText['Masterpiece'] = '<div class="card-text-coin-icon" style="transform:scale(0.53); top:-35px; display: inline;left:110px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:40px;"></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">이 카드를 구입할 때, 돈을 추가로</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">지불할 수 있다. 추가로 지불한</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">      당 은 1장을 가져온다.</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:100px; display: inline;left:40px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';

		dictText['Merchant Guild'] = '<div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+구매 1번</div></div><br><div style="display:inline;"><div style="display:inline; font-size:28px;"><div style="position: relative; left:-12px;top:1px;">+</div></div></div><br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:-20px;"></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 사용한 뒤 카드를</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">구입할 경우, <div style="display: inline; font-weight: bold;">+동전 토큰 1개</div>.</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.22); top:30px; display: inline;left:140px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
		dictText['Plaza'] = '<div style="position:relative; top:5px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div><br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 2번</div></div><br></div></div></div><div style="position:relative; top:15px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">재물 카드를 한 장을 버리면,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+동전 토큰 1개</div>.</div></div><br></div></div>';
		dictText['Taxman'] = '<div style="position:relative; top:15px;"><div style="line-height:17px;"><div style="display:inline;"><div style="display:inline; font-size:15px;">자신의 패에서 재화 카드를 한장 폐기한다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">다른 플레이어들 중 손패가 5장 이상인</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">플레이어들은 폐기된 카드와 같은 이름의</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">카드를 갖고 있을 경우, 그 카드를 버린다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">(없다면 자신의 패를 전부 공개한다.)</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">자신은 폐기한 재화의 +      의 재화 카드를</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">자신의 덱 맨 위에 올릴 수 있다.</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.15); top:130px; display: inline;left:165px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div>';
		dictText['Soothsayer'] = '<div style="position:relative; top:-15px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">금을 얻는다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">다른 플레이어들은</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">저주 카드를 얻는다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">저주 카드를 얻은 플레이어들은</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;"><div style="display:inline;font-weight:bold;">+카드 1장</div></div></div></div></div>';
		dictText['Stonemason'] = '<div style="position:relative; top:2px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">자신의 패에서 카드를 1장 폐기한다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">그보다 가격이 낮은 카드를</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">2장 얻는다.</div></div><br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:5px;"></div><div style="position:relative; top:0px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">이 카드를 구입할 때, 돈을 추가로</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">지불할 수 있다. 추가로 지불한</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">금액 이내의 액션 카드 2장을 얻는다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">(종류는 다를 수 있음)</div></div><br></div></div>';

		console.log("Load Guilds info...");
		`
	});
});