// Copyright 2018 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Called when the user clicks on the browser action.
chrome.browserAction.onClicked.addListener(function (tab) {
	chrome.tabs.executeScript(tab.ib, {
		code: 
		`
		//장막 2nd
		dictName['Courtyard'] = '안마당';
		dictText['Courtyard'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 3장</div></div><br></div></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">손에서 카드 한 장을 골라</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">당신의 덱 위에 올려놓는다.</div></div><br></div></div>';

		dictName['Conspirator'] = '공모자';
		dictText['Conspirator'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+      </div></div><br></div></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">만약 당신이 이번 턴에 지금까지</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">3장 이상의 액션 카드를 사용했다면,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:21px;"><div style="display: inline; font-weight: bold;">+ 카드 1장</div> , <div style="display: inline; font-weight: bold;">+ 액션 1번</div>.</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.24); top:-1px; display: inline;left:130px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';

		dictName['Courtier'] = '신하';
		dictText['Courtier'] = '<div style="position:relative; top:15px;"><div style="line-height:21px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">손에서 카드 1장을 공개한다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">그 카드가 가진 종류만큼 </div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">아래 4가지 중 하나씩 고른다:</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;"><div style="display: inline; font-weight: bold;">+ 액션 1번</div>;<div style="display: inline; font-weight: bold;">+ 구입 1번</div>;</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;"><div style="display: inline; font-weight: bold;">+</div>     ; 금 1장을 얻는다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">모든 선택은 서로달라야 한다.</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.15); top:121px; display: inline;left:68px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div>';


		dictName['Baron'] = '남작';
		dictText['Baron'] = '<div style="position:relative; top:5px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 구입 1번</div></div><br></div></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">손에서 사유지를 버릴 수 있다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">버리면 <div style="display: inline; font-weight: bold;">+</div>             , 아니면</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">아니면 사유지 한 장을 얻는다.</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.15); top:70px; display: inline;left:120px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div>';


		dictName['Bridge'] = '다리';
		dictText['Bridge'] = '<div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 구입 1번</div></div><br><div style="display:inline;"><div style="display:inline; font-size:28px;">+     </div></div><br></div></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">이번턴에, 모든 카드의 가격은</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">      낮아진다</div></div><br><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.22); top:30px; display: inline;left:137px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.15); top:92px; display: inline;left:90px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';


		dictName['Diplomat'] = '외교관';
		dictText['Diplomat'] = '<div style="position:relative; top:-2px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:24px;">+ 카드 2장</div></div><br></div></div><div style="position:relative; top:-5px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">그 후 패가 5장 이하라면</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;"><div style="display: inline; font-weight: bold;">+ 액션 2번</div>.</div></div><br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:2px;"></div><div style="position:relative; top:0px;"><div style="line-height:18.5px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">다른 플레이어가 공격 카드를 쓸 때,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">패가 5장 이상이라면</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">이 카드를 손에서 공개할 수 있습니다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">공개한 경우 2장을 뽑고 3장을 버린다.</div></div><br></div></div>';


		dictName['Duke'] = '공작';
		dictText['Duke'] = '<div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">덱에 있는 공작령 카드 한 장당</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">             </div></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.2); top:30px;left:135px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">1</div></div><div class="card-text-vp-icon"></div></div>';


		dictName['Harem'] = '하렘';
		dictText['Harem'] = '<div style="display:inline;"><div style="position: relative; left:-35px;"><div class="card-text-coin-icon" style="transform:scale(0.55); top:10px; display: inline;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div></div></div><br><div style="display:inline;"><div style="position: relative; left:0px;"><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.55); top:70px;left:130px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">2</div></div><div class="card-text-vp-icon"></div></div></div></div><br>';

		dictName['Nobles'] = '귀족';
		dictText['Nobles'] = '<div style="position:relative; top:-20px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">다음 중 하나를 선택한다 :<br><div style="display: inline; font-weight: bold;">+ 카드 3장</div>;</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+ 액션 2번</div>.</div></div><br></div></div><div style="position:relative; top:0px;"><div style="display:inline;"><div style="position: relative; left:0px;"><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.45); top:5px;left:130px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">2</div></div><div class="card-text-vp-icon"></div></div></div></div><br></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:-35px;"></div>';


		dictName['Ironworks'] = '철공소';
		dictText['Ironworks'] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">가격      이하의 카드를 한 장 얻는다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">당신이 얻은 카드가 ...</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;"><div style="display: inline; position: relative; left:-15px;">액션 카드라면,</div><div style="display: inline; position: relative; left:--30px;"><div style="display: inline; font-weight: bold;">+ 액션 1번</div></div></div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;"><div style="display: inline; position: relative; left:-44px;">재화 카드라면,</div><div style="display: inline; position: relative; left:-15px;"><div style="display:inline; position:relative; top:1px;"><div style="display: inline; font-weight: bold;">+     </div></div></div></div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;"><div style="display: inline; position: relative; left:-21px;">승점 카드라면,</div><div style="display: inline; position: relative; left:-0px;"><div style="display: inline; font-weight: bold;">+ 카드 1장</div></div></div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.15); top:13px; display: inline;left:45px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.15); top:95px; display: inline;left:180px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';


		dictName['Lurker'] = '잠복자';
		dictText['Lurker'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 액션 1번</div></div><br></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">다음 중 하나를 선택한다:</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">공급처에서 액션 카드 1장을 폐기한다;</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">폐기 더미에서 액션 카드를 1장 얻는다.</div></div><br></div></div>';


		dictName['Masquerade'] = '가면무도회';
		dictText['Masquerade'] = '<div style="position:relative; top:5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 2장</div></div><br></div></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">모든 플레이어는 각자의 패에서 </div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">카드 한 장을 골라</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">왼쪽 사람(나 다음에 행동하는 사람)</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">에게 동시에 넘겨줍니다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">손에 있는 카드 1장을 폐기합니다.</div></div><br></div></div>';


		dictName['Mill'] = '방앗간';
		dictText['Mill'] = '<div style="position:relative; top:-35px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 1장</div></div><br><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 액션 1번</div></div><br></div></div></div><div style="position:relative; top:-36px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:19.5px;">카드를 두 장 버리면      <div style="display: inline; font-weight: bold;">+</div>     .</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:23px; display: inline;left:239px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:-30px;"></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.5); top:65px;left:130px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">1</div></div><div class="card-text-vp-icon"></div></div>';


		dictName['Mining Village'] = '광산촌';
		dictText['Mining Village'] = '<div style="position:relative; top:-15px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 1장</div></div><br><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 액션 2번</div></div><br></div></div></div><div style="position:relative; top:0px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 폐기하면 <div style="display: inline; font-weight: bold;">+</div>     .</div></div><br></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:62px; display: inline;left:234px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';


		dictName['Minion'] = '하수인';
		dictText['Minion'] = '<div style="position:relative; top:5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 액션 1번</div></div><br></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">하나를 선택:     <div style="display: inline; font-weight: bold;">+</div>      ;         </div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">당신의 손을 모두 버리고 <div style="display: inline; font-weight: bold;">+ 카드 4장</div></div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">손이 다섯 장 이상인 다른 </div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">플레이어들은 손을 모두 버리고</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">+ 카드 4장</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:41px; display: inline;left:180px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';


		dictName['Patrol'] = '순찰대';
		dictText['Patrol'] = '<div style="position:relative; top:5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 3장</div></div><br></div></div><div style="position:relative; top:10px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">덱 맨 위의 4장을 공개한다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">공개한 카드들 중에 승점 카드나</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">저주 카드들을 내 패로 가져온다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">나머지는 내가 원하는 순서대로 </div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">덱 맨 위로 되돌려놓는다.</div></div></div></div>';


		dictName['Pawn'] = '졸개';
		dictText['Pawn'] = '<div style="position:relative; top:2px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">다음 중 서로 다른 둘을 선택한다 :</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+ 카드 1장</div>;<br><div style="display: inline; font-weight: bold;">+ 액션 1번</div>; <div style="display: inline; font-weight: bold;">+ 구입 1번</div>; <div style="display: inline; font-weight: bold;">+</div>     .</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;"></div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:55px; display: inline;left:240px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';


		dictName['Replace'] = '교체';
		dictText['Replace'] = '<div style="position:relative; top:10px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:15px;">패에서 카드 1장을 폐기한다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">폐기한 카드보다      높은 비용 한도 내에서</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">원하는 카드 1장을 얻습니다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">획득한 카드가 액션이나 재물 카드라면</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">그 카드를 덱 맨 위에 놓는다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">획득한 카드가 승점 카드라면 다른 모든 </div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">플레이어들은 각자 저주 카드를 1장 얻는다.</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.15); top:37px; display: inline;left:115px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';


		dictName['Secret Passage'] = '비밀 통로'
		dictText['Secret Passage'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 2장</div></div><br><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 액션 1번</div></div><br></div></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:21.5px;">패에서 카드 1장을 덱의</div></div><br><div style="display:inline;"><div style="display:inline; font-size:21.5px;"> 아무 곳에나 놓습니다.</div></div><br></div></div>'


		dictName['Shanty Town'] = '빈민가'
		dictText['Shanty Town'] = '<div style="position:relative; top:7px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 액션 2번</div></div><br></div></div><div style="position:relative; top:15px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">당신의 패를 공개한다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">패에 액션 카드가 없다면</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+ 카드 2장</div>.</div></div><br></div></div>'


		dictName['Steward'] = '집사'
		dictText['Steward'] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">하나를 선택: <div style="display: inline; font-weight: bold;">+ 카드 2장</div>; </div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+     ;</div></div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">패에서 카드 두 장 폐기;</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:36px; display: inline;left:135px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>'


		dictName['Swindler'] = '사기꾼'
		dictText['Swindler'] = '<div style="position:relative; top:undefinedpx;"><div style="font-weight: bold;"><div style="display:inline;">+     </div><br></div></div><div style="position:relative; top:7px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">다른 플레이어들은 덱 가장 </div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">위의 카드를 폐기하고,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">같은 가격의 당신이 </div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">선택한 카드를 한 장 얻는다.</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.24); top:0px; display: inline;left:135px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>'


		dictName['Torturer'] = '고문기술자'
		dictText['Torturer'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 3장</div></div><br></div></div><div style="position:relative; top:7px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:20.5px;">다른 플레이어들은 다음 중</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20.5px;">하나를 선택한다 :</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20.5px;">패에서 카드 2장 버리기;</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20.5px;">저주 1장 패로 가져오기;</div></div><br></div></div>'


		dictName['Trading Post'] = '교역소'
		dictText['Trading Post'] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">패에서 카드 두 장을 폐기한다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">그 뒤 은화 한 장을 </div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">패로 가져온다.</div></div><br></div></div>'


		dictName['Upgrade'] = '개선'
		dictText['Upgrade'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 1장</div></div><br><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 액션 1번</div></div><br></div></div></div><div style="position:relative; top:7px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">손에서 카드 한 장을 폐기한다. </div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">가격이 정확히 손에서 폐기한 카드의 </div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">가격이 +      인 카드 한 장을 얻어서</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">버린 덱에 둔다.</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:115px; display: inline;left:78px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>'


		dictName['Wishing Well'] = '소원의 우물'
		dictText['Wishing Well'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:25px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 카드 1장</div></div><br><div style="display:inline;"><div style="display:inline; font-size:28px;">+ 액션 1번</div></div><br></div></div></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">카드 이름 하나를 말하고, </div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">덱에서 카드 한 장을 공개한다. </div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">맞추면 손으로 가져온다. </div></div><br></div></div><div style="display:inline;"><div style="display:inline; font-size:22px;">아니라면 덱 위에 올려놓는다.</div></div>'
		
		dictBottom['Treasure - Victory'] = '재화 - 승점';
		dictBottom['Action - Victory'] = '액션 - 승점';
		
		console.log("Load Intrigue info...");
		`
	});
});
