translateName(LANGUAGE.getCardName[CardNames.BLACK_CAT], '검은 고양이');
translateName(LANGUAGE.getCardName[CardNames.SLEIGH], '썰매');
translateName(LANGUAGE.getCardName[CardNames.SUPPLIES], '보급품');
translateName(LANGUAGE.getCardName[CardNames.CAMEL_TRAIN], '낙타 대열');
translateName(LANGUAGE.getCardName[CardNames.GOATHERD], '염소지기');
translateName(LANGUAGE.getCardName[CardNames.SCRAP], '잡동사니');
translateName(LANGUAGE.getCardName[CardNames.SHEEPDOG], '목양견');
translateName(LANGUAGE.getCardName[CardNames.SNOWY_VILLAGE], '눈 덮인 마을');
translateName(LANGUAGE.getCardName[CardNames.STOCKPILE], '비축품');
translateName(LANGUAGE.getCardName[CardNames.BOUNTY_HUNTER], '현상금 사냥꾼');
translateName(LANGUAGE.getCardName[CardNames.CARDINAL], '추기경');
translateName(LANGUAGE.getCardName[CardNames.CAVALRY], '기갑 부대');
translateName(LANGUAGE.getCardName[CardNames.GROOM], '손질');
translateName(LANGUAGE.getCardName[CardNames.HOSTELRY], '민박집');
translateName(LANGUAGE.getCardName[CardNames.VILLAGE_GREEN], '공유 녹지');
translateName(LANGUAGE.getCardName[CardNames.BARGE], '바지선');
translateName(LANGUAGE.getCardName[CardNames.COVEN], '마녀 집회');
translateName(LANGUAGE.getCardName[CardNames.DISPLACE], '강제 퇴거');
translateName(LANGUAGE.getCardName[CardNames.FALCONER], '매부리');
translateName(LANGUAGE.getCardName[CardNames.FISHERMAN], '어부');
translateName(LANGUAGE.getCardName[CardNames.GATEKEEPER], '문지기');
translateName(LANGUAGE.getCardName[CardNames.HUNTING_LODGE], '사냥 오두막');
translateName(LANGUAGE.getCardName[CardNames.KILN], '가마');
translateName(LANGUAGE.getCardName[CardNames.LIVERY], '말 대여소');
translateName(LANGUAGE.getCardName[CardNames.MASTERMIND], '배후자');
translateName(LANGUAGE.getCardName[CardNames.PADDOCK], '말목장');
translateName(LANGUAGE.getCardName[CardNames.SANCTUARY], '성역');
translateName(LANGUAGE.getCardName[CardNames.DESTRIER], '군마');
translateName(LANGUAGE.getCardName[CardNames.WAYFARER], '순례자');
translateName(LANGUAGE.getCardName[CardNames.ANIMAL_FAIR], '가축 품평회');
translateName(LANGUAGE.getCardName[CardNames.HORSE], '말');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_BUTTERFLY], '나비처럼');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_CAMEL], '낙타처럼');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_CHAMELEON], '카멜레온처럼');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_FROG], '개구리처럼');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_GOAT], '염소처럼');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_HORSE], '말처럼');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_MOLE], '두더지처럼');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_MONKEY], '원숭이처럼');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_MOUSE], '생쥐처럼');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_MULE], '노새처럼');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_OTTER], '수달처럼');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_OWL], '올빼미처럼');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_OX], '황소처럼');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_PIG], '돼지처럼');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_RAT], '시궁쥐처럼');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_SEAL], '물개처럼');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_SHEEP], '양처럼');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_SQUIRREL], '다람쥐처럼');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_TURTLE], '거북이처럼');
translateName(LANGUAGE.getCardName[CardNames.WAY_OF_THE_WORM], '지렁이처럼');
translateName(LANGUAGE.getCardName[CardNames.DELAY], '지연');
translateName(LANGUAGE.getCardName[CardNames.DESPERATION], '절망');
translateName(LANGUAGE.getCardName[CardNames.GAMBLE], '도박');
translateName(LANGUAGE.getCardName[CardNames.PURSUE], '추격');
translateName(LANGUAGE.getCardName[CardNames.RIDE], '승마');
translateName(LANGUAGE.getCardName[CardNames.TOIL], '노역');
translateName(LANGUAGE.getCardName[CardNames.ENHANCE], '치장');
translateName(LANGUAGE.getCardName[CardNames.MARCH], '행군');
translateName(LANGUAGE.getCardName[CardNames.TRANSPORT], '운송');
translateName(LANGUAGE.getCardName[CardNames.BANISH], '유배');
translateName(LANGUAGE.getCardName[CardNames.BARGAIN], '흥정');
translateName(LANGUAGE.getCardName[CardNames.INVEST], '투자');
translateName(LANGUAGE.getCardName[CardNames.SEIZE_THE_DAY], '오늘을 산다');
translateName(LANGUAGE.getCardName[CardNames.COMMERCE], '상업');
translateName(LANGUAGE.getCardName[CardNames.DEMAND], '요구');
translateName(LANGUAGE.getCardName[CardNames.STAMPEDE], '폭주');
translateName(LANGUAGE.getCardName[CardNames.REAP], '수확');
translateName(LANGUAGE.getCardName[CardNames.ENCLAVE], '외국인 거주지');
translateName(LANGUAGE.getCardName[CardNames.ALLIANCE], '동맹');
translateName(LANGUAGE.getCardName[CardNames.POPULATE], '식민');


LANGUAGE.getCardText[CardNames.BLACK_CAT] = '<div style="position:relative; top:undefinedpx;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 2장</div></div></br></div></div><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">당신의 턴이 아니라면, 다른</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">플레이어들은 저주를 한 장 얻는다.</div></div></br></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:10px;"></div><div style="position:relative; top:5px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">다른 플레이어가 승점 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">얻으면, 이 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">손패에서 사용할 수 있다.</div></div></br></div></div></div>';
LANGUAGE.getCardText[CardNames.SLEIGH] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">말 카드 2장을 얻는다.</div></div></br></div></div><div style="position:relative; top:15px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">카드를 얻을 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 버리면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">얻은 카드를 손패로 가져오거나</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">덱 맨위로 올릴 수 있다.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:-87px;"></div>';
LANGUAGE.getCardText[CardNames.SUPPLIES] = '<div style="position: relative; left:-35px;top:-20px;"><div class="card-text-coin-icon" style="transform:scale(0.5); top:0px; display: inline;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div></div><div style="position:relative; top:50px;"><div style="line-height:21.5px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">말 카드 한 장을 얻어</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">덱 맨위에 둔다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.CAMEL_TRAIN] = '<div style="position:relative; top:0px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">공급처에서 승점카드 아닌</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">카드 한 장을 추방한다.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:15px;"></div><div style="position:relative; top:7px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">이 카드를 얻을 때, 공급처에서</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">금 한 장을 추방한다.</div></div></br></div></div>';

LANGUAGE.getCardText[CardNames.GOATHERD] = '<div style="position:relative; top:undefinedpx;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div></div><div style="position:relative; top:undefinedpx;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">손패에서 카드 한 장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">폐기할 수 있다.</div></div></br></div></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">당신의 오른쪽 플레이어가</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">이전 턴에 폐기한 카드 한 장 당</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+카드 1장</div></div></div></div></div>';
LANGUAGE.getCardText[CardNames.SCRAP] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">손패에서 카드 한 장을 폐기한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">폐기한 카드의         당</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">다른 것을 하나씩 선택: <div style="display: inline; font-weight: bold;">+카드 1장</div>;</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;"><div style="display: inline; font-weight: bold;">+액션 1번</div>; <div style="display: inline; font-weight: bold;">+구매 1번</div>; <div style="display: inline; font-weight: bold;">+</div>     ;</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">은 한 장 얻는다; 말 한 장 얻는다;</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:32px; display: inline;left:180px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.16); top:83px; display: inline;left:221px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText[CardNames.SHEEPDOG] = '<div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 2장</div></div></br></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:10px;"></div><div style="position:relative; top:9px;"><div style="line-height:24px;"><div style="display:inline;"><div style="display:inline; font-size:24px;">당신이 카드를 얻을 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:24px;">이 카드를 손패에서</div></div></br><div style="display:inline;"><div style="display:inline; font-size:24px;">사용할 수 있다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.SNOWY_VILLAGE] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 4번</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+구매 1번</div></div></br></div></div></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">이번 턴 이 카드를 사용한 이후,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;"><div style="display: inline; font-weight: bold;">+액션</div> 효과를 무시한다.</div></div></br></div></div>';

LANGUAGE.getCardText[CardNames.STOCKPILE] = '<div style="position: relative; left:-35px;top:-30px;"><div class="card-text-coin-icon" style="transform:scale(0.5); top:0px; display: inline;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div></div><div style="position:relative; top:40px;"><div style="font-weight: bold;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+구매 1번</div></div></br></div></div></div><div style="position:relative; top:50px;"><div style="line-height:21.5px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 사용하면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 추방한다.</div></div></div></div>';
LANGUAGE.getCardText[CardNames.BOUNTY_HUNTER] = '<div style="position:relative; top:undefinedpx;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div></div><div style="position:relative; top:15px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:19.5px;">손패에서 카드 한 장을 추방한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">추방한 카드가 추방한 카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">더미에 없는 카드라면,<div style="display: inline; font-weight: bold;">+</div>       .</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.20); top:93px; display: inline;left:227px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div>';
LANGUAGE.getCardText[CardNames.CARDINAL] = '<div style="position:relative; top:5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+   </div></div></br></div></div><div style="position:relative; top:10px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">다른 플레이어의 덱 위에서</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">카드 2장을 공개 한다. 그 중,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">비용이      에서       이하의 카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">한 장을 추방하고, 나머지는 버린다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.17); top:90px; display: inline;left:80px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.17); top:90px; display: inline;left:140px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">6</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.25); top:5px; display: inline;left:141px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText[CardNames.CAVALRY] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">말 카드 2장을 얻는다.</div></div></br></div></div><div style="position:relative; top:15px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 얻을 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+카드 2장</div>, <div style="display: inline; font-weight: bold;">+구매 1번</div></div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">구매 단계일 경우,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">액션 단계로 돌아간다.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:-87px;"></div>';

LANGUAGE.getCardText[CardNames.GROOM] = '<div style="position:relative; top:0px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">비용이        이하인 카드 한장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">얻는다. 얻은 카드가...</div></div></br></div></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:17px;"><div style="display: inline; position: relative; left:-0px;">액션카드라면, </div><div style="display: inline; position: relative; left:-0px;">말 카드 한장을 얻는다.</div></div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;"><div style="display: inline; position: relative; left:-8px;">재물카드라면, </div><div style="display: inline; position: relative; left:-8px;"><div style="display:inline; position:relative; top:undefinedpx;">은을 한 장 얻는다.</div></div></div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;"><div style="display: inline; position: relative; left:-1px;">승점카드라면,</div><div style="display: inline; position: relative; left:5px;"><div style="display: inline; font-weight: bold;">+카드 1장, +액션 1번</div></div></div></div></br></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:2px; display: inline;left:84px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div>';
LANGUAGE.getCardText[CardNames.HOSTELRY] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:24px;"><div style="display:inline;"><div style="display:inline; font-size:24px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:24px;">+액션 2번</div></div></br></div></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:10px;"></div><div style="position:relative; top:3px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">이 카드를 얻을 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">손패에서 원하는 만큼 재물카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">버릴 수 있다. 버린 카드의 개수만큼</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">말 카드를 얻는다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.VILLAGE_GREEN] = '<div style="position:relative; top:0px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이번 턴 또는</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">다음턴을 시작할 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+카드 1장</div> , <div style="display: inline; font-weight: bold;">+액션 2번.</div></div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:10px;"></div><div style="position:relative; top:3px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">정리 단계가 아닐 때 이 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">버릴 경우, 이 카드를 공개하고</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">사용할 수 있다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.BARGE] = '<div style="position:relative; top:0px;"><div style="line-height:24px;"><div style="display:inline;"><div style="display:inline; font-size:24px;">이번 턴 또는</div></div></br><div style="display:inline;"><div style="display:inline; font-size:24px;">다음턴을 시작할 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:24px;"><div style="display: inline; font-weight: bold;">+카드 3장</div> , <div style="display: inline; font-weight: bold;">+구매 1번.</div></div></div></br></div></div>';

LANGUAGE.getCardText[CardNames.COVEN] = '<div style="position:relative; top:5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+   </div></div></br></div></div><div style="position:relative; top:10px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">다른 플레이어는 공급처에서</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">저주 카드 한 장을 추방한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">더이상 추방할 수 없는 경우,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">추방더미에서 저주를 모두 버린다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.25); top:35px; display: inline;left:141px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText[CardNames.DISPLACE] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">손패에서 카드 한 장을 추방한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">추방한 카드보다 비용이         </div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">비싼 다른 이름의 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">한 장 얻는다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:37px; display: inline;left:225px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText[CardNames.FALCONER] = '<div style="position:relative; top:0px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드보다 저렴한 카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">한 장을 손패로 가져온다.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:5px;"></div><div style="position:relative; top:0px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">어떤 플레이어가 2가지</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">이상의 타입을 가진<div style="display:inline; font-size:15px;">(ex.액션-공격)</div></div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">카드를 얻을 때, 손패에서 </div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 사용 할 수 있다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.FISHERMAN] = '<div style="position:relative; top:undefinedpx;"><div style="font-weight: bold;"><div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:26px;">+액션 1번</div></div></br><div style="display:inline;"><div style="display:inline; font-size:26px;">+    </div></div></br></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.22); top:55px; display: inline;left:139px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:5px;"></div><div style="position:relative; top:0px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">당신의 턴 동안,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">버린 카드 더미가 비어있다면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17.5px;">이 카드의 가격이        만큼 내려간다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.16); top:141px; display: inline;left:141px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div>';

LANGUAGE.getCardText[CardNames.GATEKEEPER] = '<div style="position:relative; top:0px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">다음 턴을 시작할 때, <div style="display: inline; font-weight: bold;">+     </div></div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">다음 턴까지, 다른 플레이어가</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">카드를 얻으면 그 카드를 얻은 직후</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">조건에 따라 추방한다.</div></div></br><div style="position:relative; display:inline; top:5px;"><div style="display:inline; font-size:18px;">조건 : 해당 플레이어가</div></div></br><div style="position:relative; display:inline; top:0px;"><div style="display:inline; font-size:18px;">추방한 카드가 아닌</div></div></br><div style="position:relative; display:inline; top:-5px;"><div style="display:inline; font-size:18px;">액션카드 또는 재물카드</div></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:1px; display: inline;left:220px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div>';
LANGUAGE.getCardText[CardNames.HUNTING_LODGE] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 2번</div></div></br></div></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">손패를 전부 버리면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+카드 5장</div>.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.KILN] = '<div style="position:relative; top:5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+   </div></div></br></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">이번턴에 당신이 이 카드 다음에</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">사용한 카드의 효과가 발동되기 전</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">그 카드와 동일한 카드를 얻을 수 있다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.25); top:5px; display: inline;left:141px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText[CardNames.LIVERY] = '<div style="position:relative; top:5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+   </div></div></br></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이번 턴에 비용이      </div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">이상인 카드를 얻을 경우,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">말 카드 한 장을 얻는다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.25); top:5px; display: inline;left:141px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:38px; display: inline;left:212px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div>';

LANGUAGE.getCardText[CardNames.MASTERMIND] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">다음 턴을 시작할 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">액션 카드 한 장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">세 번 사용할 수 있다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.PADDOCK] = '<div style="position:relative; top:2px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+      </div></div></br></div></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">말 카드 2장을 얻는다.</div></div></br></div></div><div style="position:relative; top:20px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">비어있는 공급처 더미당, </div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+액션 1번.</div></div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.25); top:0px; display: inline;left:132px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText[CardNames.SANCTUARY] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+구매 1번</div></div></br></div></div></div><div style="position:relative; top:7px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">손패에서 카드 한 장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">추방할 수 있다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.DESTRIER] = '<div style="position:relative; top:undefinedpx;"><div style="font-weight: bold;"><div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">+카드 2장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:26px;">+액션 1번</div></div></br></div></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:5px;"></div><div style="position:relative; top:0px;"><div style="line-height:25px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">이번 턴 동안 얻은 카드 1장 당,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">이 카드의 가격은        할인.</div></div></br></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:90px; display: inline;left:185px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';

LANGUAGE.getCardText[CardNames.WAYFARER] = '<div style="position:relative; top:undefinedpx;"><div style="font-weight: bold;"><div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">+카드 3장</div></div></br></div></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">은화 한 장을 얻을 수 있다.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:15px;"></div><div style="position:relative; top:2px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드는 다른 플레이어가</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">마지막으로 얻은 카드와</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">가격이 동일해진다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.ANIMAL_FAIR] = '<div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">+      </div></div></br></div></div></div><div style="position:relative; top:0px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">비어있는 공급처 당 </div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+구매 1번</div></div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:10px;"></div><div style="position:relative; top:2px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">손패에서 액션카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">한 장을 폐기하여</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 얻을 수 있다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.22); top:-5px; display: inline;left:135px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div>';
LANGUAGE.getCardText[CardNames.HORSE] = '<div style="position:relative; top:undefinedpx;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 2장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">이 카드를 말 더미로 되돌린다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;"><div style="display: inline; font-style: italic;">(이 카드는 공급처의 카드가 아닙니다.)</div></div></div></br></div></div>';

LANGUAGE.getCardText[CardNames.WAY_OF_THE_BUTTERFLY] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">이 카드로 바꿔 사용한 액션 카드를 공급처에 돌려 놓을수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">그러면 정확히 가격이       높은 카드 한장을 얻는다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.16); top:35px; display: inline;left:196px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText[CardNames.WAY_OF_THE_CAMEL] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">금화 1장을 공급처에서 추방한다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.WAY_OF_THE_CHAMELEON] = '<div style="position:relative; top:-3px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:13px;">이 카드로 바꿔 사용한 액션카드의 효과를 아래와 같이 바꿔 사용한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;"><div style="display: inline; font-weight: bold;">+카드  </div> → <div style="display: inline; font-weight: bold;">+</div></div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;"><div style="display: inline; font-weight: bold;">+</div>       → <div style="display: inline; font-weight: bold;">+카드</div></div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:24px; display: inline;left:270px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;"></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:46px; display: inline;left:175px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;"></div></div></div>';
LANGUAGE.getCardText[CardNames.WAY_OF_THE_FROG] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">+액션 1번</div></div></br></div></div></div><div style="position:relative; top:0px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">이번 턴 이 카드로 바꿔 사용한 액션 카드 버릴수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">그러면, 그 카드를 덱 맨위로 올린다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.WAY_OF_THE_GOAT] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">손패에서 카드 한 장을 폐기한다.</div></div></br></div></div>';

LANGUAGE.getCardText[CardNames.WAY_OF_THE_HORSE] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">+카드 2장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">+액션 1번</div></div></br></div></div></div><div style="position:relative; top:0px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">이 카드로 바꿔 사용한 액션 카드를 공급처로 되돌린다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.WAY_OF_THE_MOLE] = '<div style="position:relative; top:8px;"><div style="font-weight: bold;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">+액션 1번</div></div></br></div></div></div><div style="position:relative; top:15px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">손패를 전부 버린다.<div style="display: inline; font-weight: bold;">+카드 3장</div></div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.WAY_OF_THE_MONKEY] = '<div style="position:relative; top:5px;"><div style="font-weight: bold;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">+구입 1번</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">+      </div></div><br></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:31px; display: inline;left:212px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText[CardNames.WAY_OF_THE_MOUSE] = '<div style="display:inline;"><div style="display:inline; font-size:15px;">게임 시작 전 따로 빼둔 카드를 플레이 공간에 내지 않고 사용한다.</div></div></br><div class="horizontal-line" style="width:200px; height:2px;margin-top:3px;"></div><div style="position:relative; top:-5px;"><div style="display:inline;"><div style="display:inline; font-size:13px;">게임 준비: 이번 게임에 사용하지 않은       또는      왕국 카드 하나를 따로 둔다.</div></div></br></div><div class="card-text-coin-icon" style="transform:scale(0.15); top:40px; display: inline;left:217px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.15); top:40px; display: inline;left:262px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div>';

LANGUAGE.getCardText[CardNames.WAY_OF_THE_MULE] = '<div style="position:relative; top:5px;"><div style="font-weight: bold;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">+액션 1번</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">+      </div></div></br></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:31px; display: inline;left:212px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText[CardNames.WAY_OF_THE_OTTER] = '<div style="position:relative; top:5px;"><div style="font-weight: bold;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">+카드 2장</div></div></br></div></div></div>';
LANGUAGE.getCardText[CardNames.WAY_OF_THE_OWL] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">손패가 6장이 되도록 카드를 뽑는다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.WAY_OF_THE_OX] = '<div style="position:relative; top:5px;"><div style="font-weight: bold;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">+액션 2번</div></div></br></div></div></div>';

LANGUAGE.getCardText[CardNames.WAY_OF_THE_PIG] = '<div style="position:relative; top:8px;"><div style="font-weight: bold;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">+액션 1번</div></div></br></div></div></div>';
LANGUAGE.getCardText[CardNames.WAY_OF_THE_RAT] = '<div style="position:relative; top:8px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">재물 카드 한 장을 버릴 수 있다. 그러면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">이 카드로 바꿔 사용한 액션 카드와 같은 카드를 얻는다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.WAY_OF_THE_SEAL] = '<div style="position:relative; top:3px;"><div style="font-weight: bold;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">+      </div></div></br></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:3px; display: inline;left:212px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div style="position:relative; top:0px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">이번 턴에 카드 한 장을 얻으면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">얻은 카드를 덱 맨 위에 둘 수 있다.</div></div></br></div></div>';
// LANGUAGE.getCardText[CardNames.WAY_OF_THE_SHEEP] = '';

LANGUAGE.getCardText[CardNames.WAY_OF_THE_SQUIRREL] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">정리 단계에,  <div style="display: inline; font-weight: bold;">+카드 2장</div></div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.WAY_OF_THE_TURTLE] = '<div style="position:relative; top:8px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">이 카드를 바꿔 사용한 액션 카드를 따로 둔다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">다음 턴을 시작할 때 따로 둔 액션카드를 사용한다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.WAY_OF_THE_WORM] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">사유지 한 장을 공급처에서 추방한다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.DELAY] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">손패에서 액션 카드를 따로 둘 수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">다음 턴을 시작할 때, 따로 둔 액션카드를 사용한다.</div></div></br></div></div>';

LANGUAGE.getCardText[CardNames.DESPERATION] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">한 턴에 한 번: 저주 카드를 한 장 얻을 수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">그러면, <div style="display: inline; font-weight: bold;">+구매 1번</div> 그리고 <div style="display: inline; font-weight: bold;">+</div>        .</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.20); top:29px; display: inline;left:319px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText[CardNames.GAMBLE] = '<div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:22px;">+구매 1번</div></div></br></div></div><div style="position:relative; top:-7px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">덱 맨 위의 카드 한 장을 공개한다. 공개한 카드가</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">재물이나 액션카드라면 사용할 수 있다. 아니라면 버린다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.PURSUE] = '<div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:22px;">+구매 1번</div></div></br></div></div><div style="position:relative; top:-7px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">카드 1장의 이름을 말한다. 덱 위에서 카드 4장을 공개한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">말한 카드가 있다면 덱 위로 올려두고, 나머지는 버린다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.RIDE] = '<div style="position:relative; top:5px;"><div style="line-height:24px;"><div style="display:inline;"><div style="display:inline; font-size:24px;">말 카드를 한 장 얻는다.</div></div></br></div></div>';

LANGUAGE.getCardText[CardNames.TOIL] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:22px;">+구매 1번</div></div></br></div></div><div style="position:relative; top:0px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">손패에서 액션카드 한 장을 사용할 수 있다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.ENHANCE] = '<div style="position:relative; top:5px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">손패에서 승점 카드가 아닌 카드를 한 장 폐기할 수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;">그러면, 폐기한 카드보다       높은 한도까지 카드를 한 장 얻는다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.17); top:32px; display: inline;left:175px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText[CardNames.MARCH] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">버린 카드 더미에서</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">액션카드를 사용할 수 있다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.TRANSPORT] = '<div style="position:relative; top:0px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">한 가지를 선택:</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">공급처에서 액션카드 한 장을 추방한다;</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">당신이 추방한 액션카드 한 장을 덱 위에 둔다;</div></div></br></div></div>';

LANGUAGE.getCardText[CardNames.BANISH] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">손패에서 카드 한 종류를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">원하는 만큼 추방한다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.BARGAIN] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">       이하의 승점카드가 아닌 카드 한 장을 얻는다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">다른 플레이어는 말 카드를 한 장 얻는다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:5px; display: inline;left:25px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">5</div></div></div>';
LANGUAGE.getCardText[CardNames.INVEST] = '<div style="position:relative; top:0px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">공급처에서 액션카드 한 장을 추방한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">카드가 추방된 동안 다른 플레이어가 같은 카드를 얻거나</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">투자로 같은 카드를 추방할 경우, <div style="display: inline; font-weight: bold;">+카드 2장</div>.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.SEIZE_THE_DAY] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">한 게임에 한 번:</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">이번 턴 이후, 추가 턴을 얻는다.</div></div></br></div></div>';

LANGUAGE.getCardText[CardNames.COMMERCE] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이번 턴에 얻는 다른 이름의 카드 개수 만큼</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">금화를 얻는다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.DEMAND] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">말 카드 한 장과         이하의 카드를 한 장 얻어서</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">덱 맨위에 둔다. (말 카드가 가장 위)</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.20); top:5px; display: inline;left:160px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div>';
LANGUAGE.getCardText[CardNames.STAMPEDE] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">플레이 공간에 있는 카드가 5장 이하일 경우,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">말 카드 5장을 얻어 덱 맨위에 둔다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.REAP] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">금 한 장을 얻는다. 따로 두어 다음 턴을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">시작할 때 사용한다.</div></div></br></div></div>';

LANGUAGE.getCardText[CardNames.ENCLAVE] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">금 한 장을 얻는다. 공급처에서 공작령 한 장을 추방한다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.ALLIANCE] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">속주, 공급처, 사유지, 금, 은, 동을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">각각 1장씩 얻는다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.POPULATE] = '<div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">공급처에서 모든 액션 카드를 한 장씩 얻는다.</div></div></br></div></div>';