translateName(LANGUAGE.getCardName['Bard'], '음유시인');
translateName(LANGUAGE.getCardName['Blessed Village'], '축복받은 마을');
translateName(LANGUAGE.getCardName['Changeling'], '뒤바뀐 아이');
translateName(LANGUAGE.getCardName['Cemetery'], '묘지');
translateName(LANGUAGE.getCardName['Cobbler'], '구두 수선공');
translateName(LANGUAGE.getCardName['Conclave'], '비밀 회의');
translateName(LANGUAGE.getCardName['Crypt'], '교회 지하실');
translateName(LANGUAGE.getCardName['Cursed Village'], '저주받은 마을');
translateName(LANGUAGE.getCardName['Den Of Sin'], '죄악의 소굴');
translateName(LANGUAGE.getCardName[CardNames.DEVILS_WORKSHOP], '악마의 작업장');
translateName(LANGUAGE.getCardName['Druid'], '드루이드');
translateName(LANGUAGE.getCardName['Exorcist'], '퇴마사');
translateName(LANGUAGE.getCardName['Faithful Hound'], '충직한 사냥개');
translateName(LANGUAGE.getCardName['Fool'], '바보');
translateName(LANGUAGE.getCardName['Ghost Town'], '유령도시');
translateName(LANGUAGE.getCardName['Guardian'], '수호자');
translateName(LANGUAGE.getCardName['Idol'], '우상');
translateName(LANGUAGE.getCardName['Leprechaun'], '레프러콘');
translateName(LANGUAGE.getCardName['Monastery'], '수도원');
translateName(LANGUAGE.getCardName['Necromancer'], '강령술사');
translateName(LANGUAGE.getCardName['Night Watchman'], '야간 경비원');
translateName(LANGUAGE.getCardName['Pixie'], '픽시');
translateName(LANGUAGE.getCardName['Pooka'], '푸카');
translateName(LANGUAGE.getCardName['Raider'], '습격자');
translateName(LANGUAGE.getCardName['Sacred Grove'], '신성한 숲');
translateName(LANGUAGE.getCardName['Secret Cave'], '비밀 동굴');
translateName(LANGUAGE.getCardName['Shepherd'], '양치기');
translateName(LANGUAGE.getCardName['Skulk'], '숨어 다니는 사람');
translateName(LANGUAGE.getCardName['Tormentor'], '고문자');
translateName(LANGUAGE.getCardName['Tragic Hero'], '비극적인 영웅');
translateName(LANGUAGE.getCardName['Tracker'], '추적자');
translateName(LANGUAGE.getCardName['Vampire'], '뱀파이어');
translateName(LANGUAGE.getCardName['Werewolf'], '늑대인간');

translateName(LANGUAGE.getCardName['Haunted Mirror'], '유령들린 거울');
translateName(LANGUAGE.getCardName['Magic Lamp'], '요술 램프');
translateName(LANGUAGE.getCardName['Goat'], '염소');
translateName(LANGUAGE.getCardName['Pasture'], '방목장');
translateName(LANGUAGE.getCardName['Pouch'], '주머니');
translateName(LANGUAGE.getCardName['Cursed Gold'], '저주받은 금');
translateName(LANGUAGE.getCardName['Lucky Coin'], '행운의 동전');


translateName(LANGUAGE.getCardName[CardNames.THE_EARTHS_GIFT], '대지의 선물');
translateName(LANGUAGE.getCardName[CardNames.THE_FIELDS_GIFT], '들판의 선물');
translateName(LANGUAGE.getCardName[CardNames.THE_FLAMES_GIFT], '화염의 선물');
translateName(LANGUAGE.getCardName[CardNames.THE_FORESTS_GIFT], '숲의 선물');
translateName(LANGUAGE.getCardName[CardNames.THE_MOONS_GIFT], '달의 선물');
translateName(LANGUAGE.getCardName[CardNames.THE_MOUNTAINS_GIFT], '산의 선물');
translateName(LANGUAGE.getCardName[CardNames.THE_RIVERS_GIFT], '강의 선물');
translateName(LANGUAGE.getCardName[CardNames.THE_SEAS_GIFT], '바다의 선물');
translateName(LANGUAGE.getCardName[CardNames.THE_SKYS_GIFT], '하늘의 선물');
translateName(LANGUAGE.getCardName[CardNames.THE_SUNS_GIFT], '태양의 선물');
translateName(LANGUAGE.getCardName[CardNames.THE_SWAMPS_GIFT], '늪의 선물');
translateName(LANGUAGE.getCardName[CardNames.THE_WINDS_GIFT], '바람의 선물');
translateName(LANGUAGE.getCardName['Bad Omens'], '불길한 전조');
translateName(LANGUAGE.getCardName['Delusion'], '망상');
translateName(LANGUAGE.getCardName['Envy'], '질투');
translateName(LANGUAGE.getCardName['Famine'], '기근');
translateName(LANGUAGE.getCardName['Fear'], '공포');
translateName(LANGUAGE.getCardName['Greed'], '탐욕');
translateName(LANGUAGE.getCardName['Haunting'], '빙의');
translateName(LANGUAGE.getCardName['Locusts'], '메뚜기 떼');
translateName(LANGUAGE.getCardName['Misery'], '비참');
translateName(LANGUAGE.getCardName['Plague'], '역병');
translateName(LANGUAGE.getCardName['Poverty'], '가난');
translateName(LANGUAGE.getCardName['War'], '전쟁');


translateName(LANGUAGE.getCardName[CardNames.WILL_O_WISP], '도깨비불');
translateName(LANGUAGE.getCardName[CardNames.WISH], '소원');
translateName(LANGUAGE.getCardName[CardNames.BAT], '박쥐');

translateName(LANGUAGE.getCardName[CardNames.ZOMBIE_APPRENTICE], '좀비 견습마법사');
translateName(LANGUAGE.getCardName[CardNames.ZOMBIE_MASON], '좀비 석공');
translateName(LANGUAGE.getCardName[CardNames.ZOMBIE_SPY], '좀비 첩자');

translateName(LANGUAGE.getCardName[CardNames.GHOST], '유령');

translateName(LANGUAGE.getCardName[CardNames.DELUDED], '착각');
translateName(LANGUAGE.getCardName[CardNames.ENVIOUS], '시기');
translateName(LANGUAGE.getCardName[CardNames.LOST_IN_THE_WOODS], '숲속에서 길을 잃다');
translateName(LANGUAGE.getCardName[CardNames.MISERABLE], '비참한');
translateName(LANGUAGE.getCardName[CardNames.TWICE_MISERABLE], '매우 비참한');

translateName(LANGUAGE.getCardName[CardNames.IMP], '임프');






LANGUAGE.getCardText['Bard'] = '<div style="position: relative; left:-15px;top:-15px;"><div style="font-weight: bold;"><div style="display:inline;">+</div></br></div></div><div style="line-height:50px;"><div style="display:inline;"><div style="display:inline; font-size:30px;">축복을 1장 받는다.</div></div></br></div><div class="card-text-coin-icon" style="transform:scale(0.3); top:-21px; display: inline;left:139px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText['Blessed Village'] = '<div style="font-weight: bold;"><div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:26px;">+액션 2번</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:13px;"></div><div style="position:relative; top:8px;"><div style="line-height:17.5px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">이 카드를 얻을 때, 축복을 1장 받는다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17.5px;">축복의 효과는 바로 받을 수도 있고,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17.5px;">다음 턴을 시작할 때 받을 수도 있다.</div></div></br></div></div>';
LANGUAGE.getCardText['Changeling'] = '<div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">이 카드를 폐기하고 플레이 공간에</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">있는 카드 중 1장을 복사하여 얻습니다.</div></div></br></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:13px;"></div><div style="position:relative; top:8px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">이 카드를 쓰는 게임에서      이상의</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">카드를 얻을 때, 그 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">뒤바꾼 아이로 바꿔칠 수 있습니다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:72px; display: inline;left:196px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div>';
LANGUAGE.getCardText['Cemetery'] = '<div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.55); top:-35px;left:130px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">2</div></div><div class="card-text-vp-icon"></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:40px;"></div><div style="position:relative; top:5px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">이 카드를 얻을 때 손에 있는</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">카드를 4장까지 폐기할 수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;"><div style="display: inline; font-style: italic;">(가보 : 유령들린 거울)</div></div></div></br></div></div>';

LANGUAGE.getCardText['Cobbler'] = '<div style="position:relative; top:10px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">다음 턴을 시작 할 때, 비용이</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">         이하의 카드를 얻어</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">손으로 가져온다</div></div></br></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:26px; display: inline;left:52px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div></div>';
LANGUAGE.getCardText['Conclave'] = '<div style="position: relative; left:-5px;top:-5px;"><div style="font-weight: bold;"><div style="display:inline;">+</div></br></div></div><div style="line-height:24px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">플레이 공간에 없는 액션카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">손패에서 사용할 수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">그러면, <div style="display: inline; font-weight: bold;">+액션 1번</div></div></div></br></div><div class="card-text-coin-icon" style="transform:scale(0.22); top:-5px; display: inline;left:148px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText['Crypt'] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">플레이 공간에 있는 재물 카드를 원하는</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">만큼 이 카드 밑에 뒷면으로 놓습니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">턴을 시작할 때마다, 재물 카드들을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">한 장씩 당신의 손패로 가져옵니다.</div></div></br></div></div>';
LANGUAGE.getCardText['Cursed Village'] = '<div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 2번</div></div></br></div></div><div style="position:relative; top:0px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">손패가 6장이 될 때까지</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">카드를 뽑는다.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:15px;"></div><div style="position:relative; top:7px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">이 카드를 얻을 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">주술을 1장 받는다.</div></div></br></div></div>';

LANGUAGE.getCardText['Den Of Sin'] = '<div style="position:relative; top:0px;"><div style="line-height:25px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">다음 턴을 시작할 때:</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+카드 2장</div>.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:18px;"></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">이 카드를 얻으면 손패로 들어온다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">(버리는 더미가 아니라).</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.DEVILS_WORKSHOP] = '<div style="display:inline;"><div style="display:inline; font-size:19px;">이번 턴에 얻은 카드의 수가...</div></div></br></br><div style="display:inline;"><div style="display:inline; font-size:19px;"><div style="display: inline; font-weight: bold;">2장 이상: </div>임프를 1장 얻는다;</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;"><div style="display: inline; font-weight: bold;">1장: </div>      이하의 카드를 1장 얻는다;</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;"><div style="display: inline; font-weight: bold;">0장: </div>금을 1장 얻는다;</div></div></br><div class="card-text-coin-icon" style="transform:scale(0.19); top:97px; display: inline;left:45px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div>';
LANGUAGE.getCardText['Druid'] = '<div style="position:relative; top:15px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+구매 1번</div></div></br></div></div><div style="position:relative; top:15px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">따로 둔 축복 중 하나를 받습니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">(받은 축복은 그대로 둡니다.)</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:25px;"></div><div style="position:relative; top:2px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">게임 준비 : 맨 위 축복 3장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">앞면으로 따로 둡니다.</div></div></br></div></div>';
LANGUAGE.getCardText['Exorcist'] = '<div style="position:relative; top:0px;"><div style="line-height:23px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">손에 있는 카드 한 장을 폐기하고,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">그보다 가격이 낮은 영혼 카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">한 장을 얻습니다.</div></div></br></div></div>';

LANGUAGE.getCardText['Faithful Hound'] = '<div class="card-text" style="top:20px;"><div style="font-weight: bold;"><div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 2장</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:13px;"></div><div style="position:relative; top:8px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">이 카드가 정리 단계가 아닐 때</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">버려질 경우, 이 카드를 버리는</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">대신 따로 뒀다가 그 턴이 끝난 후</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">손으로 가져올 수 있습니다.</div></div></br></div></div></div>';
LANGUAGE.getCardText['Fool'] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">당신이 <div style="display:inline; font-weight:bold;">"숲속에서 길을 잃은</div></div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display:inline; font-weight:bold;">상태"</div>가 아니라면, 그 상태를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">얻고, 3번의 축복을 원하는</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">순서대로 받는다.</div></div></br></div></div><div style="position:relative; top:15px;"><div style="display:inline;"><div style="display:inline; font-size:19px;"><div style="display: inline; font-style: italic;">(가보 : 행운의 동전)</div></div></div></br></div>';
LANGUAGE.getCardText['Ghost Town'] = '<div style="position:relative; top:0px;"><div style="line-height:25px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">다음 턴을 시작할 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+카드 1장</div>, <div style="display: inline; font-weight: bold;">+액션 1번</div>.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:18px;"></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">이 카드를 얻을 때 손패로 가져온다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">(버리는 카드 더미가 아니라).</div></div></br></div></div>';
LANGUAGE.getCardText['Guardian'] = '<div style="position:relative; top:10px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">당신의 다음 턴까지, 다른 플레이어가</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">공격 카드를 사용했을 때 당신은</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">공격 카드의 효과를 받지 않는다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">다음 턴을 시작할 때, <div style="display: inline; font-weight: bold;">+</div>     .</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.17); top:81px; display: inline;left:222px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div style="position:relative; top:20px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">이 카드를 얻을 때 손패로 가져온다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">(버리는 더미가 아니라).</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:2px;margin-top:-30px;"></div>';
// <div style="display:inline; font-weight:bold;"></div>

LANGUAGE.getCardText['Idol'] = '<div style="position: relative; left:-35px;top:-25px;"><div class="card-text-coin-icon" style="transform:scale(0.5); top:0px; display: inline;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div></div><div style="position:relative; top:40px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">이 카드를 사용할 때, 플레이 공간에</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">우상 카드의 개수가...</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">홀수 : 축복을 하나 받는다;</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;">짝수 : 다른 플레이어들은 저주를 받는다;</div></div></br></div></div>';
LANGUAGE.getCardText['Leprechaun'] = '<div style="position:relative; top:0px;"><div style="line-height:23px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">금 카드를 하나 얻는다. 플레이 공간에</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">정확히 7개의 카드가 있다면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">소원 카드를 한 장 얻는다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">아니면, 주술을 하나 받는다.</div></div></div></div>';
LANGUAGE.getCardText['Monastery'] = '<div style="position:relative; top:10px;"><div style="line-height:23px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">이번 턴에 얻은 카드 한 장당,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">손에 있는 카드 한 장 또는</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">플레이 공간에 있는 동 한 장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">폐기할 수 있습니다.</div></div></br></div></div>';
LANGUAGE.getCardText['Necromancer'] = '<div style="position:relative; top:5px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">폐기된 카드 더미에 있는,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">(앞면이고 지속 카드가 아닌)</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">액션 카드를 사용한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">사용한 카드를 그 턴 동안</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">뒷면으로 둔다.</div></div></div></div><div style="position:relative; top:15px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">게임 준비 : 좀비 카드 3장을 </div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">폐기된 카드 더미에 넣는다.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:2px;margin-top:-35px;"></div>';

LANGUAGE.getCardText['Night Watchman'] = '<div style="position:relative; top:0px;"><div style="line-height:25px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">덱 맨 위에서부터 5장을 확인하고,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">원하는 대로 버린 후 나머지를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">원하는 순서대로 덱에 되돌려 놓는다.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:8px;"></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">이 카드를 얻으면 손패로 가져옵니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">(버리는 카드더미가 아니라).</div></div></br></div></div>';
LANGUAGE.getCardText['Pixie'] = '<div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div><div style="position:relative; top:5px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">가장 위에 있는 축복을 1장 버린다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">이 카드를 폐기하면 버린 축복을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">두 번 받을 수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;"><div style="display: inline; font-style: italic;">(가보 : 염소)</div></div></div></br></div></div>';
LANGUAGE.getCardText['Pooka'] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">손패에서 "저주받은 금"이 아닌</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">재물을 하나 폐기할 수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">그러면, <div style="display: inline; font-weight: bold;">+카드 4장</div>.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;"><div style="display: inline; font-style: italic;">(가보 : 저주받은 금)</div></div></div></br></div></div>';
LANGUAGE.getCardText['Raider'] = '<div style="position:relative; top:15px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">손패가 5장 이상인 다른 플레이어들은,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">당신의 플레이 공간에 있는 카드와</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">같은 카드를 한 장 버린다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">(버릴 카드는 다른 플레이어가 선택)</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">다음 턴을 시작할 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">+       .</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:140px; display: inline;left:132px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div>';

LANGUAGE.getCardText['Sacred Grove'] = '<div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+구매 1번</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;"><div style="position: relative; left:-12px;top:1px;">+</div></div></div></br></div></div></div><div style="position:relative; top:-30px;"><div style="line-height:21px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">축복을 하나 받는다. 받은 축복에</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">+       이 없다면, 다른 플레이어도</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">같은 축복을 받을 수 있다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.22); top:25px; display: inline;left:140px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.20); top:80px; display: inline;left:20px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText['Secret Cave'] = '<div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div><div style="position:relative; top:5px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">카드 3장을 버릴 수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">그러면, 다음 턴을 시작할 때</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">              +             .</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;"><div style="display: inline; font-style: italic;">(가보 : 요술 램프)</div></div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:109px; display: inline;left:155px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div>';
LANGUAGE.getCardText['Shepherd'] = '<div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div><div style="position:relative; top:5px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">승점 카드를 원하는 만큼 버린다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">버린 승점 카드 한 장 당,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;"><div style="display: inline; font-weight: bold;">+카드 2장</div></div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;"><div style="display: inline; font-style: italic;">(가보 : 방목장)</div></div></div></br></div></div>';
LANGUAGE.getCardText['Skulk'] = '<div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+구매 1번</div></div></br></div></div><div style="position:relative; top:0px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">다른 플레이어들은</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">주술 하나를 받는다.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:15px;"></div><div style="position:relative; top:7px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 얻을 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">금을 1장 얻는다.</div></div></br></div></div>';

LANGUAGE.getCardText['Tormentor'] = '<div style="position: relative; left:-15px;top:6px;"><div style="font-weight: bold;"><div style="display:inline;">+</div></br></div></div><div style="position:relative; top:10px;"><div style="line-height:24px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">플레이 공간에 다른 카드가</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;">없다면, 임프 한 장을 얻습니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">아니면, 다른 플레이어들은</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">주술 하나를 받습니다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.22); top:5.5px; display: inline;left:140px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText['Tragic Hero'] = '<div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 3장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+구매 1번</div></div></br></div></div></br><div style="position:relative; top:-22px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">카드를 뽑은 후 8장 이상의 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">가지고 있다면, 이 카드를 폐기한</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">후 재물 카드 한 장을 얻는다.</div></div></br></div></div>';
LANGUAGE.getCardText['Tracker'] = '<div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+       </div></div></br></div></div><div style="position:relative; top:0px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">축복을 하나 받는다.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:8px;"></div><div style="position:relative; top:2px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">이 카드가 플레이 공간에 있는 동안</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">카드를 얻으면, 얻은 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">덱 맨 위에 둘 수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;"><div style="display: inline; font-style: italic;">(가보 : 주머니)</div></div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.22); top:-4px; display: inline;left:127px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText['Vampire'] = '<div style="position:relative; top:10px;"><div style="line-height:23px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">다른 플레이어들은 주술 1장 받는다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">비용이        이하인, 뱀파이어가</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">아닌 카드 하나를 얻는다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">이 카드를 박쥐로 바꾼다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:40px; display: inline;left:80px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">5</div></div></div>';
LANGUAGE.getCardText['Werewolf'] = '<div style="position:relative; top:15px;"><div style="line-height:23px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">밤 단계면, 다른 플레이어들은</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">주술 하나를 받는다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">아니면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+카드 3장</div>.</div></div></br></div></div>';



LANGUAGE.getCardText['Haunted Mirror'] = '<div class="horizontal-line" style="width:200px; height:3px;margin-top:47px;"></div><div style="position:relative; top:2px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">이 카드를 폐기할 때, 액션 카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">한 장을 버리고 유령 카드 </div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">한 장을 얻을 수 있습니다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.53); top:-35px; display: inline;left:110px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText['Magic Lamp'] = '<div style="position: relative; left:-35px;top:-25px;"><div class="card-text-coin-icon" style="transform:scale(0.5); top:0px; display: inline;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div></div><div style="position:relative; top:40px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">이 카드를 사용할 때, 만약 당신의</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">플레이 공간에 6장 이상의 카드가</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">각각 한 장씩만 존재한다면, 이 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">폐기하고 소원 카드 3장을 얻습니다.</div></div></br></div></div>';
LANGUAGE.getCardText['Goat'] = '<div style="position: relative; left:-35px;top:-30px;"><div class="card-text-coin-icon" style="transform:scale(0.5); top:0px; display: inline;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div></div><div style="position:relative; top:40px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 사용할 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">당신의 손에서 카드 한 장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">폐기할 수 있습니다.</div></div></br></div></div>';

LANGUAGE.getCardText['Pasture'] = '<div class="horizontal-line" style="width:200px; height:3px;margin-top:47px;"></div><div style="position:relative; top:12px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">사유지 한 장당 </div></div></br></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.53); top:-35px; display: inline;left:110px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.18); top:64px;left:226px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">1</div></div><div class="card-text-vp-icon"></div></div>';
LANGUAGE.getCardText['Pouch'] = '<div style="position: relative; left:-35px;top:-40px;"><div class="card-text-coin-icon" style="transform:scale(0.5); top:0px; display: inline;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div></div><div style="position:relative; top:35px;"><div style="font-weight: bold;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:23px;">+구매 1번</div></div></br></div></div></div>';
LANGUAGE.getCardText['Cursed Gold'] = '<div style="position: relative; left:-35px;top:-30px;"><div class="card-text-coin-icon" style="transform:scale(0.5); top:0px; display: inline;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div></div><div style="position:relative; top:40px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 사용할 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">저주 한 장을 얻습니다.</div></div></br></div></div>';
LANGUAGE.getCardText['Lucky Coin'] = '<div style="position: relative; left:-35px;top:-30px;"><div class="card-text-coin-icon" style="transform:scale(0.5); top:0px; display: inline;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div></div><div style="position:relative; top:40px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 사용할 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">은 카드를 한 장 얻습니다.</div></div></br></div></div>';


LANGUAGE.getCardText[CardNames.THE_EARTHS_GIFT] = '<div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">재물 카드를 하나 버리고</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">         이하의 카드를 하나 얻을 수 있다.</div></div></br></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:30px; display: inline;left:65px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div>';
LANGUAGE.getCardText[CardNames.THE_FIELDS_GIFT] = '<div style="font-weight: bold;"><div style="line-height:25px;"><div style="display:inline;"><div style="display:inline; font-size:25px;">+액션 1번</div></div></br><div style="display:inline;"><div style="display:inline; font-size:25px;"><div style="position: relative; left:-13px;top:1px;">+</div></div></div></br></div></div><div style="position:relative; top:-32px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">(정리 단계까지 유지한다.)</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:26px; display: inline;left:218px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText[CardNames.THE_FLAMES_GIFT] = '<div style="display:inline;"><div style="display:inline; font-size:24px;">손패에서 카드 한 장을 폐기할 수 있다.</div></div></br>';
LANGUAGE.getCardText[CardNames.THE_FORESTS_GIFT] = '<div style="font-weight: bold;"><div style="line-height:25px;"><div style="display:inline;"><div style="display:inline; font-size:25px;">+구매 1번</div></div></br><div style="display:inline;"><div style="display:inline; font-size:25px;"><div style="position: relative; left:-13px;top:1px;">+</div></div></div></br></div></div><div style="position:relative; top:-32px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">(정리 단계까지 유지한다.)</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:26px; display: inline;left:218px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';

LANGUAGE.getCardText[CardNames.THE_MOONS_GIFT] = '<div style="display:inline;"><div style="display:inline; font-size:22px;">버리는 카드 더미를 보고,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">카드 하나를 덱 맨 위에 올릴 수 있다.</div></div></br>';
LANGUAGE.getCardText[CardNames.THE_MOUNTAINS_GIFT] = '<div style="display:inline;"><div style="display:inline; font-size:26px;">은을 한 장 얻는다.</div></div></br>';
LANGUAGE.getCardText[CardNames.THE_RIVERS_GIFT] = '<div style="display:inline;"><div style="display:inline; font-size:22px;">정리 단계에서(이 턴이 끝날 때) <div style="display: inline; font-weight: bold;">+카드 1장</div></div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">(정리 단계까지 유지한다.)</div></div></br>';
LANGUAGE.getCardText[CardNames.THE_SEAS_GIFT] = '<div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br></div>';
LANGUAGE.getCardText[CardNames.THE_SKYS_GIFT] = '<div style="display:inline;"><div style="display:inline; font-size:22px;">카드를 3장 버리고 금을 하나 얻을 수 있다.</div></div></br>';
LANGUAGE.getCardText[CardNames.THE_SUNS_GIFT] = '<div style="display:inline;"><div style="display:inline; font-size:16px;">덱의 맨 위에서부터 4장의 카드를 본다. 그 중 원하는</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">대로 버린 후 나머지를 원하는 순서대로 덱 위에 돌려놓는다.</div></div></br>';
LANGUAGE.getCardText[CardNames.THE_SWAMPS_GIFT] = '<div style="display:inline;"><div style="display:inline; font-size:26px;">도깨비불 한 장을 얻는다.</div></div></br>';
LANGUAGE.getCardText[CardNames.THE_WINDS_GIFT] = '<div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:26px;">+카드 2장</div></div></br></div><div style="display:inline;"><div style="display:inline; font-size:23px;">카드를 2장 버린다.</div></div></br>';

LANGUAGE.getCardText['Bad Omens'] = '<div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">덱을 버리는 카드 더미에 둔다. 버리는 카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">더미를 살펴본 후, 동 2장을 덱 맨 위에 둔다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">(또는 그렇게 할 수 없음을 보여준다.)</div></div></br></div>';
LANGUAGE.getCardText['Delusion'] = '<div style="display:inline;"><div style="display:inline; font-size:18px;">"망상에 빠짐"이나 "질투에 빠짐" 상태가 아니라면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;"><div style="display:inline; font-weight:bold;">"망상에 빠짐"</div> 상태가 된다.</div></div></br>';
LANGUAGE.getCardText['Envy'] = '<div style="display:inline;"><div style="display:inline; font-size:18px;">"망상에 빠짐"이나 "질투에 빠짐" 상태가 아니라면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">"질투에 빠짐" 상태가 된다.</div></div></br>';
LANGUAGE.getCardText['Famine'] = '<div style="display:inline;"><div style="display:inline; font-size:18px;">덱 맨 위에서부터 3장의 카드를 공개한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">그 중 액션 카드들을 버린 후, 나머지를 덱에 넣고 섞는다.</div></div></br>';

LANGUAGE.getCardText['Fear'] = '<div style="display:inline;"><div style="display:inline; font-size:22px;">손패에 카드를 5장 이상 들고 있다면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">액션 또는 재물 카드를 하나 버린다.</div></div></br>';
LANGUAGE.getCardText['Greed'] = '<div style="display:inline;"><div style="display:inline; font-size:26px;">동 한장을 얻어 덱 맨 위에 올린다.</div></div></br>';
LANGUAGE.getCardText['Haunting'] = '<div style="display:inline;"><div style="display:inline; font-size:26px;">손패에 카드를 4장 이상 들고 있다면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:26px;">그 중 하나를 덱 맨 위에 올려둔다.</div></div></br>';
LANGUAGE.getCardText['Locusts'] = '<div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">덱의 맨 위 카드를 폐기한다. 폐기한 카드가</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">동이나 사유지라면, 저주를 얻는다. 아니면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">그것과 같은 종류의 더 저렴한 카드를 얻는다.</div></div></br></div>';

LANGUAGE.getCardText['Misery'] = '<div style="display:inline;"><div style="display:inline; font-size:15px;">이번 게임에서 처음으로 뽑은 비참이라면, "비참함" 상태에 빠진다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;">아니라면, "비참함"을 뒤집어 "매우 비참함" 상태에 빠진다.</div></div></br>';
LANGUAGE.getCardText['Plague'] = '<div style="display:inline;"><div style="display:inline; font-size:26px;">저주 한 장을 손패로 가져온다.</div></div></br>';
LANGUAGE.getCardText['Poverty'] = '<div style="display:inline;"><div style="display:inline; font-size:16px;">손패에 있는 카드를 3장까지만 남기고 모두 버린다.</div></div></br>';
LANGUAGE.getCardText['War'] = '<div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">비용이          또는        인 카드가 나올 때까지</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">덱에서 카드를 공개한다. 그 카드를 폐기하고</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">나머지를 버린다.</div></div></br><div class="card-text-coin-icon" style="transform:scale(0.18); top:2px; display: inline;left:120px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:40px;">3</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:2px; display: inline;left:190px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:40px;">4</div></div></div></div>';

LANGUAGE.getCardText[CardNames.WILL_O_WISP] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div></div><div style="position:relative; top:5px;"><div style="line-height:21px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">덱 맨 위 카드 한 장을 공개한다. 만약 </div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">공개한 카드의 가격이        이하라면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">손패에 넣는다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;"><div style="display: inline; font-style: italic;">(이 카드는 공급처의 카드가 아닙니다.)</div></div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.17); top:89px; display: inline;left:175px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText[CardNames.WISH] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div><div style="position:relative; top:15px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">이 카드를 소원 더미로 되돌린다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">그러면, 가격이       이하의</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">카드를 손패로 가져온다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;"><div style="display: inline; font-style: italic;">(이 카드는 공급처의 카드가 아닙니다.)</div></div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:68px; display: inline;left:163px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">6</div></div></div>';
LANGUAGE.getCardText[CardNames.BAT] = '<div style="position:relative; top:15px;"><div style="line-height:23px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">손패에서 카드를 두 장까지</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">폐기한다. 하나 이상 폐기했다면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;">이 카드를 뱀파이어로 바꾼다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;"><div style="display: inline; font-style: italic;">(이 카드는 공급처의 카드가 아닙니다.)</div></div></div></br></div></div>';


LANGUAGE.getCardText[CardNames.ZOMBIE_APPRENTICE] = '<div style="position:relative; top:15px;"><div style="line-height:23px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">손패에서 액션 카드 </div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">한 장을 폐기하면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+카드 3장</div></div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+액션 1번</div></div></div></div></div>';
LANGUAGE.getCardText[CardNames.ZOMBIE_MASON] = '<div style="position:relative; top:50px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">덱 맨 위에서 한 장을 폐기한다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">폐기한 카드보다      높은</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">비용 한도 내에서</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">카드 1장을 얻을 수 있다.</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:23px; display: inline;left:183px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div></div>';
LANGUAGE.getCardText[CardNames.ZOMBIE_SPY] = '<div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div><div style="position:relative; top:10px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">덱 맨 위의 카드 한 장을 확인하고</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">버릴지 되돌릴지 결정한다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.GHOST] = '<div style="position:relative; top:15px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">액션카드가 나올때까지 덱을 공개한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">액션카드를 따로 두고 나머지는 버린다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">다음 턴을 시작할 때, 공개한 액션카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">두 번 사용한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;"><div style="display: inline; font-style: italic;">(이 카드는 공급처의 카드가 아닙니다.)</div></div></div></br></div></div>';


LANGUAGE.getCardText[CardNames.DELUDED] = '<div style="display:inline;"><div style="display:inline; font-size:22px;">구매 단계를 시작할 때, 이 카드를 되돌린다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">이번 턴에 액션 카드를 구매할 수 없다.</div></div><br>';
LANGUAGE.getCardText[CardNames.ENVIOUS] = '<div style="display:inline;"><div style="display:inline; font-size:22px;">구매 단계를 시작할 때, 이 카드를 되돌린다.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">이번 턴에 은과 금은       의 가치를 가진다.</div></div><br><div class="card-text-coin-icon" style="transform:scale(0.20); top:34px; display: inline;left:220px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText[CardNames.LOST_IN_THE_WOODS] = '<div style="display:inline;"><div style="display:inline; font-size:26px;">턴을 시작 할때, 카드 한장을 버리면</div></div><br><div style="display:inline;"><div style="display:inline; font-size:26px;">축복을 하나 받는다.</div></div><br>';
// LANGUAGE.getCardText['MISERABLE'] = '';
// LANGUAGE.getCardText['TWICE MISERABLE'] = '';


LANGUAGE.getCardText[CardNames.IMP] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 2장</div></div></br></div></div><div style="position:relative; top:15px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">플레이 공간에 없는</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">액션카드 한 장을 손패에서</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">사용할 수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;"><div style="display: inline; font-style: italic;">(이 카드는 공급처의 카드가 아닙니다.)</div></div></div></br></div></div>';
