translateName(LANGUAGE.getCardName['Sauna'], '사우나');
translateName(LANGUAGE.getCardName['Black Market'], '암시장');
translateName(LANGUAGE.getCardName['Envoy'], '사절');
translateName(LANGUAGE.getCardName['Governor'], '총독');
translateName(LANGUAGE.getCardName['Prince'], '왕자');
translateName(LANGUAGE.getCardName['Walled Village'], '벽이 있는 마을');
translateName(LANGUAGE.getCardName['Dismantle'], '분해');
translateName(LANGUAGE.getCardName['Captain'], '선장');
translateName(LANGUAGE.getCardName['Church'], '교회');
translateName(LANGUAGE.getCardName['Summon'], '소환');


LANGUAGE.getCardText['Sauna'] = '<div style="font-weight: bold;"><div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:27px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:27px;">+액션 1번</div></div></br></div></div><div style="position:relative; top:-2px;"><div style="line-height:19.5px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">손패에 아반토 카드가 있다면</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">추가로 사용 할 수 있습니다.</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:2px;"></div><div style="position:relative; top:-1px;"><div style="line-height:19.5px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">이 카드를 사용했을 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">은을 사용 한다면 손패에서</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">1장을 폐기 할 수 있습니다.</div></div></br></div></div>';
LANGUAGE.getCardText['Black Market'] = '<div style="position:relative; top:1px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:26px;">+   </div></div></br></div></div><div style="position:relative; top:-2px;"><div style="line-height:15px;"><div style="display:inline;"><div style="display:inline; font-size:15px;">암시장 덱 맨 위 카드 3장을 공개합니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;">공개된 카드 중 1장을 구매할 수 있습니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;">구입하지 않은 카드는 암시장 덱 맨 아래에</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;">원하는 순서대로 놓습니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;">(카드를 구매하는 것으로 보지 않습니다.)</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.24); top:2px; display: inline;left:140px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div><div class="horizontal-line" style="width:200px; height:2px;margin-top:3px;"></div><div style="position:relative; top:-1px;"><div style="line-height:11px;"><div style="display:inline;"><div style="display:inline; font-size:14px;">준비 단계 : 게임을 시작하기 전에 공급처에</div></div></br><div style="display:inline;"><div style="display:inline; font-size:14px;">포함되지 않은 왕국 카드를 종류별로</div></div></br><div style="display:inline;"><div style="display:inline; font-size:14px;">1장씩 모아 암시장 덱을 만듭니다.</div></div></div></div>';
LANGUAGE.getCardText['Envoy'] = '<div style="position:relative; top:7px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">자기 덱 맨 위 카드 5장을 공개합니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">다음 플레이어가 그 중에서 버릴 카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">1장을 대신 고릅니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">나머지 카드들은 손으로 가져옵니다.</div></div></br></div></div>';
LANGUAGE.getCardText['Governor'] = '<div style="position:relative; top:-2px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:20px;">+액션 1번</div></div></br></div></div><div style="position:relative; left:10px; top:-5px; text-align:left;"><div style="line-height:10.5px;"><div style="display:inline;"><div style="display:inline; font-size:14px;">하나를 선택합니다 :</div></div></br><div style="display:inline;"><div style="display:inline; font-size:14px;">자신은 금을 얻고,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:14px;">다른 플레이어들은 은을 얻습니다;</div></div></br><div style="display:inline; position:relative; top:5px;"><div style="display:inline; font-size:14px;">자신은 <div style="display:inline; font-weight:bold;">+카드 3장</div></div></div></br><div style="display:inline; position:relative; top:5px;"><div style="display:inline; font-size:14px;">다른 플레이어들은 <div style="display:inline; font-weight:bold;">+카드 1장</div>;</div></div></br><div style="display:inline; position:relative; top:10px;"><div style="display:inline; font-size:14px;">자신은 손패에서 카드 한 장을 폐기하고</div></div></br><div style="display:inline; position:relative; top:10px;"><div style="display:inline; font-size:14px;">정확히       비싼 카드를 얻습니다.</div></div></br><div style="display:inline; position:relative; top:10px;"><div style="display:inline; font-size:14px;">다른 플레이어들은 손패에서 카드 한 장씩을</div></div></br><div style="display:inline; position:relative; top:10px;"><div style="display:inline; font-size:14px;">폐기하고 정확히       비싼 카드를 얻습니다.</div></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.13); top:130px; display: inline;left:55px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.13); top:162px; display: inline;left:115px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';

LANGUAGE.getCardText['Prince'] = '<div style="position:relative; top:15px;"><div style="line-height:17.5px;"><div style="display:inline;"><div style="display:inline; font-size:14px;">이 카드를 따로 둘 수 있습니다. 그러면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:14px;">손패에서          이하의 액션 카드 한 장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:14px;">따로 둡니다. 자신의 차례를 시작할 때마다,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:14px;">그 액션 카드를 사용하고 플레이 공간에서</div></div></br><div style="display:inline;"><div style="display:inline; font-size:14px;">버려지게 될 때 그 카드를 다시 따로 둡니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:14px;">(만약 그 카드를 사용한 차례에 다시 따로</div></div></br><div style="display:inline;"><div style="display:inline; font-size:13px;">두지 못하게 됐다면 사용을 계속할 수 없습니다.)</div></div></br></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.16); top:38px; display: inline;left:85px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div>';
LANGUAGE.getCardText['Walled Village'] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 2번</div></div></br></div></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:5px;"></div><div style="position:relative; top:1px;"><div style="line-height:20.5px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">정리 단계 때 사용중인 액션 카드가</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">이 카드를 포함하여 2장 이내 일 경우,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">이 카드를 덱 맨 위로</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">올려둘 수 있습니다.</div></div></br></div></div>';
LANGUAGE.getCardText['Dismantle'] = '<div style="position:relative; top:7px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">손에 있는 카드 중 1장을 폐기합니다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">폐기한 카드가        이상일 경우,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">폐기한 카드보다 저렴한</div></div></br><div style="display:inline;"><div style="display:inline; font-size:17px;">카드 1장과 금 1장을 얻습니다.</div></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:33px; display: inline;left:140px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText['Captain'] = '<div style="position:relative; top:7px;"><div style="line-height:22px;"></br><div style="display:inline;"><div style="display:inline; font-size:18px;">이번 턴과 다음 턴을 시작할 때:</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">공급처에 있는 가격이         까지인</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">액션카드를 사용한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">(지속카드와 명령카드는 제외)</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">(사용하는 카드는 공급처에 둔다.)</div></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:55px; display: inline;left:190px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div>';

LANGUAGE.getCardText['Church'] = '<div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">손패에서 3장까지 뒷면으로 따로 둔다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">다음 턴을 시작할 때, 따로 둔 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">손패로 가져온다. 손패에서 카드 한 장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">폐기할 수 있다.</div></div></br></br></div></div>';
LANGUAGE.getCardText['Summon'] = '<div style="display:inline;"><div style="display:inline; font-size:20px;">      이하의 액션 카드를 얻어서 따로 둡니다.<div class="card-text-coin-icon" style="transform:scale(0.18); top:5px; display: inline;left:24px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div></div></div></br><div style="display:inline;"><div style="display:inline; font-size:15px;">그러면, 자신의 다음 턴을 시작할 때 따로 둔 카드를 사용합니다.</div></div></br>';
