translateName(LANGUAGE.getCardName[CardNames.ACTING_TROUPE], "연극단");
translateName(LANGUAGE.getCardName[CardNames.BORDER_GUARD], "국경 수비대");
translateName(LANGUAGE.getCardName[CardNames.CARGO_SHIP], "화물선");
translateName(LANGUAGE.getCardName[CardNames.DUCAT], "두카트");
translateName(LANGUAGE.getCardName[CardNames.EXPERIMENT], "실험");
translateName(LANGUAGE.getCardName[CardNames.FLAG_BEARER], "기수");
translateName(LANGUAGE.getCardName[CardNames.HIDEOUT], "은신처");
translateName(LANGUAGE.getCardName[CardNames.INVENTOR], "발명가");
translateName(LANGUAGE.getCardName[CardNames.IMPROVE], "증축");
translateName(LANGUAGE.getCardName[CardNames.LACKEYS], "하인");
translateName(LANGUAGE.getCardName[CardNames.MOUNTAIN_VILLAGE], "산촌");
translateName(LANGUAGE.getCardName[CardNames.PATRON], "후원자");
translateName(LANGUAGE.getCardName[CardNames.PRIEST], "사제");
translateName(LANGUAGE.getCardName[CardNames.RESEARCH], "연구");
translateName(LANGUAGE.getCardName[CardNames.SILK_MERCHANT], "비단상");
translateName(LANGUAGE.getCardName[CardNames.OLD_WITCH], "늙은 마녀");
translateName(LANGUAGE.getCardName[CardNames.RECRUITER], "신병 모집");
translateName(LANGUAGE.getCardName[CardNames.SCEPTER], "홀");
translateName(LANGUAGE.getCardName[CardNames.SCHOLAR], "학자");
translateName(LANGUAGE.getCardName[CardNames.SCULPTOR], "조각가");
translateName(LANGUAGE.getCardName[CardNames.SEER], "예언자");
translateName(LANGUAGE.getCardName[CardNames.SPICES], "향신료");
translateName(LANGUAGE.getCardName[CardNames.SWASHBUCKLER], "마릴린몬로");
translateName(LANGUAGE.getCardName[CardNames.TREASURER], "회계사");
translateName(LANGUAGE.getCardName[CardNames.VILLAIN], "악당");
translateName(LANGUAGE.getCardName[CardNames.FLAG], "깃발");
translateName(LANGUAGE.getCardName[CardNames.HORN], "뿔피리");
translateName(LANGUAGE.getCardName[CardNames.KEY], "열쇠");
translateName(LANGUAGE.getCardName[CardNames.LANTERN], "랜턴");
translateName(LANGUAGE.getCardName[CardNames.TREASURE_CHEST], "보물 상자");
translateName(LANGUAGE.getCardName[CardNames.ACADEMY], "아카데미");
translateName(LANGUAGE.getCardName[CardNames.BARRACKS], "병영");
translateName(LANGUAGE.getCardName[CardNames.CANAL], "운하");
translateName(LANGUAGE.getCardName[CardNames.CAPITALISM], "자본주의");
translateName(LANGUAGE.getCardName[CardNames.CATHEDRAL], "대성당");
translateName(LANGUAGE.getCardName[CardNames.CITADEL], "성채");
translateName(LANGUAGE.getCardName[CardNames.CITY_GATE], "시문");
translateName(LANGUAGE.getCardName[CardNames.CROP_ROTATION], "윤작");
translateName(LANGUAGE.getCardName[CardNames.EXPLORATION], "탐험");
translateName(LANGUAGE.getCardName[CardNames.FAIR], "장터");
translateName(LANGUAGE.getCardName[CardNames.FLEET], "선단");
translateName(LANGUAGE.getCardName[CardNames.GUILDHALL], "길드 집회소");
translateName(LANGUAGE.getCardName[CardNames.INNOVATION], "혁신");
translateName(LANGUAGE.getCardName[CardNames.PAGEANT], "야외극");
translateName(LANGUAGE.getCardName[CardNames.PIAZZA], "피아차");
translateName(LANGUAGE.getCardName[CardNames.ROAD_NETWORK], "도로망");
translateName(LANGUAGE.getCardName[CardNames.SEWERS], "하수관");
translateName(LANGUAGE.getCardName[CardNames.SILOS], "곡식 저장고");
translateName(LANGUAGE.getCardName[CardNames.SINISTER_PLOT], "사악한 음모");
translateName(LANGUAGE.getCardName[CardNames.STAR_CHART], "별자리표");



LANGUAGE.getCardText[CardNames.ACTING_TROUPE] = '<div style="position:relative; top:10px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+주민 토큰 4개</div></div></br></div><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 폐기한다.</div></div></br></div>';
LANGUAGE.getCardText[CardNames.BORDER_GUARD] = '<div style="position:relative; top:5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">덱 위에서 카드 2장을 공개한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">한장은 손패에 넣고 한장은 버린다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">둘 다 액션 카드일 경우, 랜턴이나</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">뿔피리를 얻는다.</div></div></br></br></div></div>';
LANGUAGE.getCardText[CardNames.CARGO_SHIP] = '<div style="position:relative; top:3px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+      </div></div></br></div></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">이번 턴에 한 번, 당신이 </div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">카드를 얻을 때 얻은 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">이 카드위에 둘 수 있다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">다음 턴을 시작할 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">따로 둔 카드를 손패로 가져온다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.25); top:2px; display: inline;left:131px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText[CardNames.DUCAT] = '<div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">+동전 토큰 1개</div></div></br><div style="display:inline;"><div style="display:inline; font-size:26px;">+구매 1번</div></div></br></div></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:5px;"></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 얻을 때, 손패에서</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">동 하나를 폐기할 수 있다.</div></div></br></div></div>';

LANGUAGE.getCardText[CardNames.EXPERIMENT] = '<div style="position:relative; top:undefinedpx;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 2장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div><div style="line-height:21px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">이 카드를 공급처로 되돌린다.</div></div></br></div><div class="horizontal-line" style="width:250px; height:3px;margin-top:10px;"></div><div style="line-height:21px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">이 카드를 얻을 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;">실험 한 장을 얻는다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;">(연속되지 않는다.)</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.FLAG_BEARER] = '<div style="position:relative; top:-20px;"><div style="font-weight: bold;"><div style="line-height:25px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+      </div></div></br></div></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:10px;"></div><div style="position:relative; top:20px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 얻거나 폐기할 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">깃발을 받는다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.25); top:-22px; display: inline;left:131px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText[CardNames.HIDEOUT] = '<div style="position:relative; top:0px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 2번</div></div></br></div></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">손패에서 카드 한 장을 폐기한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">폐기한 카드가 승점카드라면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:19px;">저주 한 장을 얻는다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.INVENTOR] = '<div style="position:relative; top:10px;"><div style="line-height:23px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">비용이         이하인 카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">한 장을 얻는다. 이번 턴에</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">모든 카드의 가격은        할인.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:8px; display: inline;left:104px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:61px; display: inline;left:197px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';

LANGUAGE.getCardText[CardNames.IMPROVE] = '<div style="position:relative; top:3px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+      </div></div></br></div></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">정리 단계를 시작할 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">이번 턴에 플레이 공간에서</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">버려질 액션 카드 하나를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">폐기하고 정확히      </div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">비싼 카드를 하나 얻는다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.25); top:2px; display: inline;left:131px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:110px; display: inline;left:210px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText[CardNames.LACKEYS] = '<div style="position:relative; top:-10px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 2장</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:10px;"></div><div style="position:relative; top:12px;"><div style="line-height:24px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 얻을 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+주민 토큰 2개</div>.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.MOUNTAIN_VILLAGE] = '<div style="position:relative; top:10px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 2번</div></div></br></div></div><div style="position:relative; top:25px;"><div style="line-height:21px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">버린 카드 더미에서</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">카드 한 장을 손패로 가져온다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;">가져올 수 없다면, <div style="display: inline; font-weight: bold;">+카드 1장</div>.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.PATRON] = '<div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="line-height:32px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+주민 토큰 1개</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+   </div></div></br></div></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:5px;"></div><div style="position:relative; top:undefinedpx;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">다른 카드의 효과로 이 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">공개할 경우</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+동전 토큰 1개</div>.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.25); top:28px; display: inline;left:143px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';

LANGUAGE.getCardText[CardNames.PRIEST] = '<div style="position:relative; top:3px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+      </div></div></br></div></div></div><div style="position:relative; top:18px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">손패에서 카드 한 장을 폐기한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">이번 턴 동안 카드를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">폐기할 때 마다, <div style="display: inline; font-weight: bold;">+</div>     .</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.25); top:2px; display: inline;left:131px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:97px; display: inline;left:208px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText[CardNames.RESEARCH] = '<div style="position:relative; top:3px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div></div><div style="position:relative; top:10px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">손패에서 카드 한 장을 폐기한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">폐기한 카드의        만큼</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">덱 위에서 카드를 가져와 이 카드</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">위에 둔다. 다음 턴을 시작할 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">따로 둔 카드를 손패로 가져온다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:63px; display: inline;left:171px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText[CardNames.SILK_MERCHANT] = '<div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 2장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+구매 1번</div></div></br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:15px;"></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 얻거나 폐기할 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;"><div style="display: inline; font-weight: bold;">+동전 토큰 1개</div> , <div style="display: inline; font-weight: bold;">+주민 토큰 1개</div>.</div></div></br></div></div></div>';
LANGUAGE.getCardText[CardNames.OLD_WITCH] = '<div style="position:relative; top:10px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 3장</div></div></br></div></div></div><div style="position:relative; top:15px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">다른 플레이어들은 저주 한 장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">얻는다. 다른 플레이어들은 </div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">손패에서 저주 한 장을</div></div></br></div><div style="display:inline;"><div style="display:inline; font-size:22px;">폐기할 수 있다.</div></div></div>';

LANGUAGE.getCardText[CardNames.RECRUITER] = '<div style="position:relative; top:-3px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 2장</div></div></br></div></div></div><div style="position:relative; top:15px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">손패에서 카드 한장을 폐기한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">폐기한 카드의        마다</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+주민 토큰 1개</div></div></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:68px; display: inline;left:184px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';
LANGUAGE.getCardText[CardNames.SCEPTER] = '<div style="position:relative; top:15px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">하나를 선택한다:</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+      </div>;</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">플레이 공간에 남아있는</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">액션 카드를 다시 사용한다;</div></div></br></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:41px; display: inline;left:135px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText[CardNames.SCHOLAR] = '<div style="position:relative; top:10px;"><div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">손패를 모두 버린다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:26px;"><div style="display: inline; font-weight: bold;">+카드 7장</div>.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.SCULPTOR] = '<div style="position:relative; top:0px;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:23px;">비용이       이하인 </div></div></br><div style="display:inline;"><div style="display:inline; font-size:23px;">카드를 손패로 가져온다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:23px;">얻은 카드가 재물카드라면, </div></div></br><div style="display:inline;"><div style="display:inline; font-size:23px;"><div style="display: inline; font-weight: bold;">+주민 토큰 1개</div>.</div></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.22); top:2px; display: inline;left:128px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div>';

LANGUAGE.getCardText[CardNames.SEER] = '<div style="position:relative; top:5px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 1장</div></div></br><div style="display:inline;"><div style="display:inline; font-size:28px;">+액션 1번</div></div></br></div></div></div><div style="position:relative; top:5px;"><div style="line-height:21px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">덱 위에서 카드 3장을 공개한다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">그 중 비용이        부터          까지인</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">카드 한 장을 손패로 가져온다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">나머지는 원하는 순서대로 돌려놓는다.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.17); top:88px; display: inline;left:114px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.17); top:88px; display: inline;left:184px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div>';
LANGUAGE.getCardText[CardNames.SPICES] = '<div style="position: relative; left:-25px;top:-30px;"><div class="card-text-coin-icon" style="transform:scale(0.4); top:0px; display: inline;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div></div><div style="position:relative; top:25px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+구매 1번</div></div></br></div></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:30px;"></div><div style="position:relative; top:5px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">이 카드를 얻을 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+동전 토큰 2개</div>.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.SWASHBUCKLER] = '<div style="position:relative; top:10px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+카드 3장</div></div></br></div></div></div><div style="position:relative; top:18px;"><div style="line-height:21px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">버려진 카드 더미에 카드가</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">한 장이라도 있다면, <div style="display: inline; font-weight: bold;">+동전 토큰 1개</div>.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">만약 4개 이상의 동전 토큰이 있다면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">보물 상자를 받습니다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.TREASURER] = '<div style="position:relative; top:5px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+   </div></div></br></div></div></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">하나를 선택: 손패에서</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">재물 카드 한장을 폐기한다;</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">폐기된 재물 카드 중 하나를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">손패로 가져온다;</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">열쇠를 받는다;</div></div></div></div><div class="card-text-coin-icon" style="transform:scale(0.25); top:4px; display: inline;left:142px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div>';

LANGUAGE.getCardText[CardNames.VILLAIN] = '<div style="position:relative; top:10px;"><div style="font-weight: bold;"><div style="line-height:28px;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+동전 토큰 2개</div></div></br></div></div></div><div style="position:relative; top:20px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">손패가 5장 이상인 다른</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">플레이어들은 비용이        </div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">이상인 카드 한 장을 버린다.</div></div></br></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:73px; display: inline;left:229px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div>';
LANGUAGE.getCardText[CardNames.FLAG] = '<div style="position:relative; top:10px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">정리 단계에서, <div style="display: inline; font-weight: bold;">+카드 1장</div>.</div></div></br></div>';
LANGUAGE.getCardText[CardNames.HORN] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">한 턴에 한 번, 플레이 공간에서 국경 수비대를</div></div></br><div style="display:inline;"><div style="display:inline; font-size:20px;">버릴때, 덱 맨위로 올릴 수 있다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.KEY] = '<div style="position:relative; top:10px;"><div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">턴을 시작할 때,             <div style="display: inline; font-weight: bold;">+</div>      .</div></div></br></div><div class="card-text-coin-icon" style="transform:scale(0.24); top:0px; display: inline;left:338px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div></div>';

LANGUAGE.getCardText[CardNames.LANTERN] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">국경 수비대가 덱에서 3장을 공개하고 2장을 버리게 만든다.</div></div></br><div style="display:inline;"><div style="display:inline; font-size:16px;">(뿔피리를 얻기 위해서는 3장 모두 액션카드.)</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.TREASURE_CHEST] = '<div style="position:relative; top:10px;"><div style="line-height:24px;"><div style="display:inline;"><div style="display:inline; font-size:24px;">구매 단계를 시작할 때, 금을 한 장 얻는다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.ACADEMY] = '<div style="position:relative; top:10px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">액션 카드를 얻을 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:26px;"><div style="display: inline; font-weight: bold;">+주민 토큰 1개</div>.</div></div></br>';
LANGUAGE.getCardText[CardNames.BARRACKS] = '<div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">턴을 시작할 때, <div style="display: inline; font-weight: bold;">+액션 1번</div>.</div></div></br></div>';

LANGUAGE.getCardText[CardNames.CANAL] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">당신의 턴 동안 모든 카드의 가격이      할인.</div></div></br></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:0px; display: inline;left:350px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div></div>';
LANGUAGE.getCardText[CardNames.CAPITALISM] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">당신의 턴 동안, <div style="display:inline; font-weight:bold;">+</div>      가 있는 액션카드의</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">타입에 재물이 추가됩니다. <div style="display:inline; font-size:14px;">(재물카드를 낼 때 사용 가능)</div></div></div></br></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:0px; display: inline;left:198px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;"></div></div></div></div>';
LANGUAGE.getCardText[CardNames.CATHEDRAL] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">턴을 시작할 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">손패에서 카드 한 장을 폐기한다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.CITADEL] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">처음으로 사용한 액션카드를 사용한 후에,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">한 번 더 사용합니다.</div></div></br></div></div>';

LANGUAGE.getCardText[CardNames.CITY_GATE] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">턴을 시작할 때, <div style="display: inline; font-weight: bold;">+카드 1장</div>,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">손패에서 카드 한 장을 덱위에 올린다.</div></div><br></div></div>';
LANGUAGE.getCardText[CardNames.CROP_ROTATION] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">턴을 시작할 때 승점 카드 한 장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">버리면, <div style="display: inline; font-weight: bold;">+카드 2장</div>.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.EXPLORATION] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">구매 단계가 끝날 때, 어떤 카드도 구매하지</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">않았다면, <div style="display: inline; font-weight: bold;">+동전 토큰 1개</div> , <div style="display: inline; font-weight: bold;">+주민 토큰 1개</div>.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.FAIR] = '<div style="position:relative; top:10px;"><div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">턴을 시작할 때, <div style="display: inline; font-weight: bold;">+구매 1번</div>.</div></div></br></div></div>';

LANGUAGE.getCardText[CardNames.FLEET] = '<div style="position:relative; top:25px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">게임이 끝난 뒤, 추가 턴을 진행합니다.</div></div></br></br></div></div>';
LANGUAGE.getCardText[CardNames.GUILDHALL] = '<div style="position:relative; top:10px;"><div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">재물 카드를 얻을 때, <div style="display: inline; font-weight: bold;">+동전 토큰 1개</div>.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.INNOVATION] = '<div style="position:relative; top:10px;"><div style="line-height:21px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">이번 턴에 처음으로 얻은 액션 카드를 따로</div></div></br><div style="display:inline;"><div style="display:inline; font-size:21px;">둘 수 있다. 그러면, 따로 둔 카드를 사용한다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.PAGEANT] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">구매 단계가 끝날 때,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">       을 지불하면 <div style="display: inline; font-weight: bold;">+동전 토큰 1개</div>.</div></div></br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:34px; display: inline;left:75px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>';

LANGUAGE.getCardText[CardNames.PIAZZA] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">턴을 시작할 때, 덱 맨위에서 카드 한 장을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">공개한다. 액션 카드라면 사용한다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.ROAD_NETWORK] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">다른 플레이어가 승점 카드를 얻으면,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+카드 1장</div>.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.SEWERS] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">하수관이 아닌 다른 방법으로 카드를 폐기할 경우,</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">손패에서 카드 한 장을 폐기할 수 있다.</div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.SILOS] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">턴을 시작할 때, 손패에서 원하는 만큼 동을</div></div></br><div style="display:inline;"><div style="display:inline; font-size:18px;">버립니다. 버린 개수 만큼 카드를 공개하고 <div style="display:inline; font-weight:bold;">+카드</div></div></div></br></div></div>';

LANGUAGE.getCardText[CardNames.SINISTER_PLOT] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">턴을 시작할 때, 여기에 토큰을 추가하거나;</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">토큰을 제거하고 개수 만큼 <div style="display: inline; font-weight: bold;">+카드 1장</div></div></div></br></div></div>';
LANGUAGE.getCardText[CardNames.STAR_CHART] = '<div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">덱을 섞을 때, 카드 한 장을 선택하여</div></div></br><div style="display:inline;"><div style="display:inline; font-size:22px;">덱 맨위에 둘 수 있다.</div></div></br></div></div>';